### ISSUE TITLE
Create Flatpak package

### ISSUE THREAD

**Issue by Alexander-Wilms** [elementary/mail#124]
Since there haven't been many commits to Geary's codebase in the recent months, and since you're targeting other distros as well, it might make sense to provide a Flatpak.

One could probably reuse parts of Geary's build manifest and I tried creating a new one for Pantheon Mail, but it failed due to https://github.com/elementary/mail/issues/8.

**Comment by tintou** [comment]
We're currently rewriting Pantheon Mail so the Geary manifest will probably be different

**Comment by Alexander-Wilms** [comment]
Makes sense. I'll try again once the rewrite is complete, if someone else wants to have a go, here's the current manifest:

`{
	"app-id": "org.pantheon.mail",
	"runtime": "org.gnome.Platform",
	"runtime-version": "3.24",
	"sdk": "org.gnome.Sdk",
	"finish-args": [
		"--filesystem=host",

		"--socket=wayland",
		"--socket=x11",

		"--share=network",

		"--talk-name=org.gtk.vfs",
		"--talk-name=org.gtk.vfs.*",
		"--talk-name=org.gnome.SettingsDaemon",

		"--filesystem=xdg-run/dconf",
		"--filesystem=xdg-config/dconf:ro",
		"--talk-name=ca.desrt.dconf",
		"--env=DCONF_USER_CONFIG_DIR=.config/dconf"
	],
	"build-options": {
		"cflags": "-O2",
		"cxxflags": "-O2"
	},
	"cleanup": [
		"/bin/granite-demo",
		"/bin/peas-demo",
		"/share/applications/granite-demo.desktop",
		"/include",
		"/lib/pkgconfig",
		"/lib/peas-demo",
		"/share/vala",
		"/man",
		"*.a",
		"*.la"
	],
	"modules": [
		{
			"name": "libgee",
			"build-options": {
				"env": {
					"PKG_CONFIG_GOBJECT_INTROSPECTION_1_0_GIRDIR": "/app/share/gir-1.0",
					"PKG_CONFIG_GOBJECT_INTROSPECTION_1_0_TYPELIBDIR": "/app/lib/girepository-1.0"
				}
			},
			"sources": [
				{
					"type": "archive",
					"url": "https://github.com/GNOME/libgee/archive/0.20.0.tar.gz",
					"sha256": "42fe6d651910cb8b720167f71c5255a1b7b1afc82fecd3f31e61f9602b3b1335"
				}
			]
		},
		{
			"name": "granite",
			"buildsystem": "cmake",
			"config-opts": [
				"-DCMAKE_BUILD_TYPE=Release",
				"-DCMAKE_INSTALL_LIBDIR=/app/lib"
			],
			"build-options": {
				"env": {
					"PKG_CONFIG_GOBJECT_INTROSPECTION_1_0_GIRDIR": "/app/share/gir-1.0",
					"PKG_CONFIG_GOBJECT_INTROSPECTION_1_0_TYPELIBDIR": "/app/lib/girepository-1.0"
				}
			},
			"sources": [
				{
					"type": "archive",
					"url": "https://github.com/elementary/granite/archive/0.4.1.tar.gz",
					"sha256": "035a9b36ef73352ff8a76be06b876d9e2ea6633abb693fb67297d998c8d3a240"
				}
			]
		},
		{
			"name": "libxml2",
			"config-opts": [
				"--without-python"
			],
			"sources": [
				{
					"type": "archive",
					"url": "https://git.gnome.org/browse/libxml2/snapshot/libxml2-2.9.4.tar.xz",
					"sha256": "85b83a6ed144b75e7f63eca0d3c10f1cbab17ffd9a1edecf0b9554f9728cbece"
				}
			]
		},
		{
			"name": "mail",
			"buildsystem": "cmake",
			"sources": [
				{
					"type": "git",
					"url": "https://github.com/elementary/mail.git"
				}
			]
		}
	]
}`

**Comment by MrMarukesu** [comment]
the app-id should be io.elementary.mail

**Comment by Marukesu** [comment]
Need to build the icons with the package.
```
Renaming io.elementary.mail.appdata.xml to share/appdata/io.elementary.mail.appdata.xml
Renaming icon elementary/apps/16/internet-mail.svg to elementary/apps/16/io.elementary.mail.svg
Renaming icon elementary/apps/64/internet-mail.svg to elementary/apps/64/io.elementary.mail.svg
Renaming icon elementary/apps/symbolic/internet-mail-symbolic.svg to elementary/apps/symbolic/io.elementary.mail-symbolic.svg
Renaming icon elementary/apps/48/internet-mail.svg to elementary/apps/48/io.elementary.mail.svg
Renaming icon elementary/apps/32/internet-mail.svg to elementary/apps/32/io.elementary.mail.svg
Renaming icon elementary/apps/24/internet-mail.svg to elementary/apps/24/io.elementary.mail.svg
Renaming icon elementary/apps/128/internet-mail.svg to elementary/apps/128/io.elementary.mail.svg
Rewriting contents of io.elementary.mail.desktop
Running appstream-compose
Processing application io.elementary.mail
Error loading desktop file: Failed to find icon: Failed to find icon io.elementary.mail
Error: ERROR: appstream-compose failed: Child process exited with code 1
```
