### ISSUE TITLE
Patheon mail forget html signature.

### ISSUE THREAD

**Issue by rogerlmiranda** [elementary/mail#134]
When use two mail account whith custom html signature, after reboot OS, patheon mail forget html signature. Verifying geary.ini, i see the file has been reseted.

**Comment by rogerlmiranda** [comment]
I just realized that the problem occurs when the email account is added using "Online Accounts" in "System Settings". If you remove the email accounts from "online accounts" and add the email account directly to patheon mail the problem does not occur.

**Comment by jegjessing** [comment]
Well, I did not have the account in Online Accounts but experienced the problem. I then read the problem could be that one had to add it to Online Accounts to fix the problem. Witch it did not :-1: 
So I'm not convinced that that is a solution either way. I'm still struggling with the problem.

**Comment by croozey** [comment]
I also have this problem. The signature seems to disappear if I kill / end the app from System Monitor after the app hangs (which often happens after entering a 1-character search string in "Search Mail"). When the app is restarted, some settings are reset (e.g. Storage / Download mail & Composer / Sign emails). Hope this helps track down the bug... I have the latest version - 1.0.6 (i.e. all updates applied).

**Comment by janxkoci** [comment]
I think this is no longer relevant as the current version does not even have this feature. After the recent backend switch, lots of features need to be implemented again, including signatures.

**Consider closing or repurposing the ticket to track new implementation of support for signatures.**

**Comment by danirabbit** [comment]
Closing since we've re-implemented signatures and they seem to work as expected across sessions
