### ISSUE TITLE
Alternative to Geary Mail

### ISSUE THREAD

**Issue by btd1337** [elementary/mail#155]
Hy, elementary team,

As you know Mail has some bugs that persist for a long time.
We still suffer with the window bug growing infinitely and this is not good for new users.

However I want to leave a tip:

The N1 Nylas team has made it open-source and encourages your fork.
The community is keeping the project well.

It is more complete, with fewer bugs and with a closer look to eOS's standard and open-source!

Consider taking a look at the project.

Original Style:
![n1-1](https://user-images.githubusercontent.com/11943860/31081589-bd9d8dec-a762-11e7-815b-4bcf0de9741f.png)

elementary OS full  theme:

![elementary](https://user-images.githubusercontent.com/11943860/31081621-d6511584-a762-11e7-9703-727953e6f2f5.png)

elementary OS soft theme:
![elementarysoft](https://user-images.githubusercontent.com/11943860/31081622-d651aeae-a762-11e7-8e66-2ee4fed364d4.png)

Original project: https://github.com/nylas/nylas-mail
Community project: https://github.com/nylas-mail-lives/nylas-mail
eOS themes: http://www.n1themes.com/

**Comment by snwh** [comment]
Pretty much every software project has persistent bugs, and forking a different project means inheriting all their bugs (which we did already with Geary -> Mail) and Nylas Mail has over 1000 issues on its GitHub page. Not to mention, Nylas Mail is built using toolkits that are not "native" to the elementary platform (Electron, React, etc.) which makes it unnecessarily large. So I don't think we'll be doing this, but feel free to continue to use Nylas Mail with the elementary theme.

**Comment by danrabbit** [comment]
Closing this as "Won't Fix". Rest assured however that we're working on a fresh Mail codebase that does not seem to exhibit the infinite window width bug

**Comment by btd1337** [comment]
However the bugs referred to Nylas do not prevent you from using the application, they are small bugs, most suggestions for improvements.

Meanwhile Geary Mail when opening begins to grow the window infinitely.

How to use?

The first thing we have to do when installing elementary OS is to remove Geary and install Thunderbird!

And who needs the mail?

Nylas is multiplatform, if you get support from the Windows, MacOS and Linux community, is not this considerable?

Since the elementary Freya can not use Geary without the problem of the window does not stop growing, I find it troubling that the main client of the system can not be used.
