### ISSUE TITLE
Mail doesn't always open in foreground

### ISSUE THREAD

**Issue by jtrees** [elementary/mail#156]
### Steps to Reproduce
1. Open a few applications.
2. Open Mail via the dock.

### Expected Result
The Mail window opens above all other windows.

### Actual Result
The Mail window opens behind some other windows. Sometimes this results in Mail being hidden completely.

### Additional Info
Mail v1.0.6

**Comment by ryonakano** [comment]
Probably because of https://github.com/elementary/gala/issues/1

**Comment by ryonakano** [comment]
Just a note, this is when you launch Mail via dock. #215 is via Applications-menu.

**Comment by danrabbit** [comment]
Thanks for your report! We've done a from-scratch rewrite of Mail and I can't reproduce this with the new version of Mail. I'm closing this report since I can't reproduce it any longer
