### ISSUE TITLE
Use EDS backend for contacts

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mail#16]
Think this is the plan, but right now Mail only uses its internal database of known emails for suggestions. Instead, we should tap into EDS to get email addresses it knows about as well.

**Comment by josephholsten** [comment]
Anything I can do to contribute to this? Got any rough designs I could attempt wiring up?

What's the scope of this? An entire address book with CRUD for card entries? A fuzzy finder across the range of names and addresses in the compose ui's To: CC:, BCC: fields? Any integration into search?

**Comment by danrabbit** [comment]
Closing because in the rewrite we're using libfolks which uses EDS as a source
