### ISSUE TITLE
Weird window size bug

### ISSUE THREAD

**Issue by kingogames** [elementary/mail#162]
When I opened up Geary today, the window spans wider than the screen and is super narrow. I can't resize the window or maximize, I can only close it.
![screenshot from 2017-10-30 16 09 00](https://user-images.githubusercontent.com/13295856/32253847-ca538462-be62-11e7-8309-ce78d9748ff3.png)

**Comment by josephholsten** [comment]
@kingogames did you figure out how to get out of the situation? and then perhaps how to reproduce it?

**Comment by btkostner** [comment]
Could this be related to: https://github.com/elementary/mail/issues/1?

**Comment by AlonsoEnrique** [comment]
Same here: 
![crazymail](https://user-images.githubusercontent.com/1877511/33439942-b8c34356-d5bc-11e7-93ce-4d5a464e795a.gif)

**Comment by danrabbit** [comment]
Closing as a duplicate of #1
