### ISSUE TITLE
AppCenter page for Mail points to Launchpad

### ISSUE THREAD

**Issue by josephholsten** [elementary/mail#167]
What I did:
- Went to the AppCenter page for Mail at https://appcenter.elementary.io/org.pantheon.mail.desktop
- Clicked the "Report an Problem" link.

What I expected:
- To be brought to https://github.com/elementary/mail/issues or https://github.com/elementary/mail/issues/new

What Happened:
- Was brought to https://bugs.launchpad.net/pantheon-mail

NB: Current [AppData](https://github.com/elementary/mail/blob/master/data/org.pantheon.mail.appdata.xml.in#L80) seems to point to github, maybe merely a release is needed?

**Comment by danrabbit** [comment]
Should be fixed as of the last release
