### ISSUE TITLE
Move to Trash key binding doesn't always work

### ISSUE THREAD

**Issue by josephholsten** [elementary/mail#169]
What I did:
- select a message in **Inbox**
- press `<Backspace>`

What I expected:
- the message to disappear from view, be removed from **Inbox**, and be added to **Trash**
toWhat happened instead:
- nothing, so far as I can tell

Nota bene:
- same behaviour for `<Delete>` on this message
- many other messages delete just fine
- I'm not seeing any doc here about enabling higher levels of debugging, or otherwise guiding me about how to investigate & fix this on my own. I'd love to help, but currently only know how to investigate this with strace or gdb. Does something slightly less painful exist?

**Comment by flojon** [comment]
I'm having the same problem.
I've tried:
- Delete
- Backsapce
- Trash icon button
- Right click the message and choose "Delete Conversation"

It does however work if I select multiple messages and right click and choose "Delete conversation"

This is using an IMAP account.

**Comment by flojon** [comment]
I ran latest from master with the debug flag and then I see this in the log:

```
 [deb] 14:34:47 0,000172 imap-engine-generic-account.vala:617: Previously used Trash for special folder GEARY_SPECIAL_FOLDER_TYPE_TRASH
 [deb] 14:34:47 0,000029 imap-engine-generic-account.vala:661: Creating Trash to use as special folder GEARY_SPECIAL_FOLDER_TYPE_TRASH
 [deb] 14:34:47 0,040147 imap-client-session.vala:1043: [0001/mail.example.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_AUTHORIZED] Received error from server: a027 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.)
 [deb] 14:34:47 0,000595 geary-controller.vala:2501: Unable to archive/trash/delete messages: Server reports error creating path Trash: a027 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.)
 ```

So seems to be a namespace issue. Cannot find a setting for namespace in account...

**Comment by flojon** [comment]
Created a Trash folder using my web mail and then I can delete again.

**Comment by danirabbit** [comment]
I think this can be closed as a Geary-engine related bug
