### ISSUE TITLE
fast way to archive

### ISSUE THREAD

**Issue by snowparrot** [elementary/mail#17]
In Mail there should be an one-click way to archive an email. (or move it to a customized folder)

**Comment by cassidyjames** [comment]
If you're using a Gmail account or if your mail server has a folder named "Archive", then you should have the "Archive conversation" button in the headerbar, or can hit the shortcut (the A key) to archive.

**Comment by cassidyjames** [comment]
@snowparrot can you provide more details as to what you expect, or if the Archive button isn't showing for you?

**Comment by marbetschar** [comment]
@cassidyjames my Archive button is missing in Mail too - at least for all Exchange/Office365 accounts. My Non-Exchange accounts to have the following buttons:

![Screenshot from 2020-01-13 21-25-02](https://user-images.githubusercontent.com/392542/72289547-a3fdfc80-364b-11ea-8e6b-4c698a7fb53d.png)

Wherelse in the Exchange accounts, the button bar looks like this:

![Screenshot from 2020-01-13 21-24-46](https://user-images.githubusercontent.com/392542/72289583-b710cc80-364b-11ea-8ec5-2da93aa8147f.png)

Although the Exchange accounts definetely have an Archive folder (I used the very same accounts together with Apple Mail and archived a lot of emails in them - in additon, I also made sure the folders are there server side).

What I'm missing here?

**Comment by marbetschar** [comment]
Found a workaround for missing Archive button in Exchange accounts: Don't add the Mail account with "Service: Outlook.com", instead use "Service: Other" and enter the [IMAP and SMTP connection details as documented](https://support.office.com/en-us/article/POP-IMAP-and-SMTP-settings-for-Outlook-com-d088b986-291d-42b8-9564-9c414e2aa040).

This way you'll get the Archive button as well as the Archive Quick Action (`A`) for Exchange accounts.

**Comment by danirabbit** [comment]
Gonna close this since it seems like maybe it was a Geary engine bug
