### ISSUE TITLE
resize ever expanding

### ISSUE THREAD

**Issue by bksubhuti** [elementary/mail#181]
This issue was on launchpad but I figured it is best to post here.

The screen seems to ever expand.  I cannot resize it either.

What I did to get this bug.
I set two step verification.  Afterwards the pwd was not valid.  I had to set the app password in google.
This failed pwd caused the bug to happen.  

I deleted my profile directory so I could reset the login information.
Bug is still there.

**Comment by btkostner** [comment]
Closing as a duplicate of #1
