### ISSUE TITLE
Gmail with two-factor auth = fail

### ISSUE THREAD

**Issue by mrsergvit** [elementary/mail#182]
The app looks nice, but I can't login to mine gmail account.
It shows me a message about wrong entry data, but data is ok.
One different - enabled two-factor authorization.

**Comment by tintou** [comment]
Duplicate of #41

**Comment by gudge25** [comment]
Still cant login Gmail with two-factor auth

**Comment by ryonakano** [comment]
@gudge25 See https://github.com/elementary/mail/issues/41#issuecomment-407006652
