### ISSUE TITLE
root of imap mail

### ISSUE THREAD

**Issue by JO0st** [elementary/mail#193]
I recently added a new imap email account. It already has folder for sent email and trash. However they are subfolders of inbox. 
![image](https://user-images.githubusercontent.com/4729613/37147616-d2f87446-22c7-11e8-9759-ec673f8e9615.png)
This makes that send mails are not saved in the sent folder, and that deleting mails is not possible. 
In the manual to add the email address to other mail clients I found two approaches: outlook makes it possible to [change the root of your imap folders ](https://help.one.com/hc/en-us/articles/115005594485-Setting-up-Microsoft-Outlook-2016). I think this will also take care of recognising the sent and trash folder.
Apple mail takes another approach to this: it makes the [send and trash folders configurable](https://help.one.com/hc/en-us/articles/115005594545-Setting-up-Mail-OS-X-Sierra)

This is the debug output when trying to delete an email:
```
[deb] 12:15:23 3,480955 geary-controller.vala:2465: Trashing selected messages
 [deb] 12:15:23 0,000129 imap-engine-generic-account.vala:617: Previously used Prullenbak for special folder GEARY_SPECIAL_FOLDER_TYPE_TRASH
 [deb] 12:15:23 0,000028 imap-engine-generic-account.vala:661: Creating Prullenbak to use as special folder GEARY_SPECIAL_FOLDER_TYPE_TRASH
 [deb] 12:15:24 0,040837 imap-client-session.vala:1043: [0004/imap.one.com/default:993 GEARY_IMAP_CLIENT_SESSION_STATE_AUTHORIZED] Received error from server: a008 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs) .
 [deb] 12:15:24 0,000736 geary-controller.vala:2501: Unable to archive/trash/delete messages: Server reports error creating path Prullenbak: a008 NO Client tried to access nonexistent namespace. (Mailbox name should probably be prefixed with: INBOX.) (0.000 + 0.000 secs) .
```

**Comment by danirabbit** [comment]
Closing as a geary engine issue. This likely can't be reproduced now that we're using EDS
