### ISSUE TITLE
Insert URL dialog's default text is redundant

### ISSUE THREAD

**Issue by uncertainquark** [elementary/mail#197]
The dialog inputs the following text by default:
![screenshot from 2018-03-18 14-41-23](https://user-images.githubusercontent.com/22585732/37862999-98f704e4-2f7c-11e8-92c4-8e89ce46e102.png)
On opening the dialog box, the text doesn't get selected automatically so that the user can paste the copied URL from the clipboard and have the text replaced.

The user is much more likely to paste an existing copied URL from the clipboard rather than typing the URL in the dialog box, which is why 
1. Either remove the default text
2. Or auto-select it on pop up so that it gets replaced on a paste action from clipboard

**Comment by jlnr** [comment]
And `http://` is the wrong placeholder in the age of `https://` anyway :)

**Comment by uncertainquark** [comment]
Note: The new Geary version (0.12.x) has this fixed. The "Insert URL" dialog box opens to "http'//" selected by default. Perhaps the fix could be imported from there?

**Comment by snowparrot** [comment]
Why dont you use a pop-over instead of a dialog?

**Comment by arshubham** [comment]
@danrabbit can you add a provision to enter email too. See how gmail handles it, it has a radio buttons to select if you want to enter link or email.

**Comment by danrabbit** [comment]
@arshubham Please open a new, separate issue report for additional feature requests
