### ISSUE TITLE
Delete key doesn't delete message in the "Thrash" folder

### ISSUE THREAD

**Issue by uncertainjatan** [elementary/mail#199]
![screenshot from 2018-03-25 13 58 52](https://user-images.githubusercontent.com/22585732/37873584-3d7c7434-303d-11e8-8f6e-2e12aa0ee7e4.png)

Delete key doesn't work in the Thrash folder for either single message delete or batch delete. It works in the "Spam" folder though.

**Comment by ryonakano** [comment]
I can't confirm this issue with the latest master of Mail. Feel free to reopen if you're still facing it with the latest master
