### ISSUE TITLE
Cannot insert images in mail body

### ISSUE THREAD

**Issue by luispablo** [elementary/mail#20]
When building an HTML mail, I can use an image as an attached file, but I cannot insert it in the mail body, along with the text.

Neither can I save in my computer, nor download, an embedded image when someone sends me an e-mail with an image inside the mail body.

**Comment by janxkoci** [comment]
@danrabbit Please notice that the merge request only dealth with the first part of OP's problem. The second part - saving received embedded images - still doesn't work in current version. There are now a [few](https://elementaryos.stackexchange.com/questions/19203/cant-save-photos-from-email/19706#19706) [questions](https://elementaryos.stackexchange.com/questions/19703/saving-photos-from-the-mail-app) about it on elementary SE.
