### ISSUE TITLE
Window keeps stretching horizontally

### ISSUE THREAD

**Issue by aadilayub** [elementary/mail#222]
![gifout](https://user-images.githubusercontent.com/31581044/42145482-7765bbc4-7df4-11e8-847e-f8c2ff28d9c6.gif)

This has happened a few times before. The window just keeps stretching horizontally every time I open the mail app. A restart did not fix it. 

Experiencing this issue on eOS Loki running on a Lenovo G40-45.

**Comment by ryonakano** [comment]
I suppose this is duplication of #1
