### ISSUE TITLE
Today I broke the mail app

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/mail#241]
![screenshot from 2018-09-26 11-55-52](https://user-images.githubusercontent.com/25323231/46058961-655adf00-c187-11e8-8623-863382775316.png)
Any idea what cause this?

**Comment by danrabbit** [comment]
Closing as a duplicate of #1

**Comment by WattanaGaming** [comment]
For bug sake its not the same problem. it happens then i resize the width of inbox list too far, not when launching
