### ISSUE TITLE
Discussion: Use/Extend Evolution Mail to use with Elementary OS

### ISSUE THREAD

**Issue by mahajanudit** [elementary/mail#244]
Just opening this issue as a discussion rather than a request or bug.
Mail which is mainly forked from Geary seems to fall really short of a mail client as far as functionality and usability goes. Evolution mail, which off course is very clunky doesn't seem to fit well with eOS design but as far as the functionality goes, it really packs all.
There are a few issues with it as far as UI/UX go and functionality enhancement like "Mail thread from All Mail", and/or reduce preferences etc.
But it seems that make these enhancements might be more worthwhile than investing in Mail.
I am not a designer, but perhaps if someone can comeup with realistic modern designs of Evolution, it might be a good idea to see if it works better than Mail.
Again, at this point this is just a discussion and the output I am hoping for if at all would be mockups of Evolution and outlining of feature enhancement.
Thoughts?

**Comment by tintou** [comment]
We are currently rewriting this application (in https://github.com/elementary/mail/tree/rewrite ) to use Evolution-Data-Server as a backend making it use the same technology as Evolution itself.

**Comment by mahajanudit** [comment]
@tintou curious are there any mockups of the rewrite?

**Comment by tintou** [comment]
@mahajanudit it is basically the same UI but with a different backend
