### ISSUE TITLE
Emoji picker in the composer

### ISSUE THREAD

**Issue by danrabbit** [elementary/mail#250]
Now that we support color emoji, we should have an emoji picker in the composer

**Comment by cassidyjames** [comment]
Like, a button to open the emoji picker? Is this a pattern we want to do broadly?

**Comment by dracid** [comment]
In the [Medium](https://medium.com/elementaryos/elementary-os-5-juno-is-here-471dfdedc7b3) announcement, it says that we can insert emojis in the native app text fields.
Mail is probably the ONLY elementary app you'd actually want to use this in. 
Yes, emoji picker would be good here.

**Comment by danrabbit** [comment]
@cassidyjames I'm not sure if we have other cases in default apps for it? The problem in Mail is that the composer widget isn't a Gtk widget, it's a webkit view IIRC because it has to render markup that Gtk.TextView can't do. There's no built in support in this view for the Gtk emoji picker as far as I can see, so it needs something obvious to help out

**Comment by cassidyjames** [comment]
@danrabbit gotcha, yeah if the compose view has to be WebKit, then WebKit will need to gain support for GTK emoji input to make this easy. But for now, we could _probably_ do something somewhat hacky with an invisible Gtk.Entry and the `insert_emoji` signal, then paste the contents of that entry into the message. Kind of like what I was poking at in [Ideogram](https://github.com/cassidyjames/ideogram). 

The major disadvantage I see to this is that I haven't found a way to reliably detect the closing of the popover (to return focus to the WebKit view), and the popover will point at wherever the invisible entry is, not where the user's cursor is in the WebKit view.

**Comment by dracid** [comment]
Ideogram sounds like exactly the kind of utility you'd use in non-native apps, for chatting, etc!
Is there a precedent to implementing something similar to this? 
Can one hack it to something like "pasting a symbol from clipboard on closure of the emoji dialog"?

**Comment by dracid** [comment]
I've just stumble upon an idea!!
Why not use the same principle the OnBoard virtual keyboard works? It works in ALL apps, right? 
What we have is basically a virtual keyboard for EMOJIS, instead of language characters.

**Comment by cassidyjames** [comment]
@dracid please keep this issue focused on the Mail app specifically. A system-wide emoji picker is quite beyond the scope of this repo.

**Comment by dracid** [comment]
> @dracid please keep this issue focused on the Mail app specifically. A system-wide emoji picker is quite beyond the scope of this repo.

Funny thing. Wouldn't a system-wide emoji picker SOLVE this problem automatically (and many others)? Where does the current emoji picker WORK?

**Comment by danrabbit** [comment]
It seems like maybe this was fixed upstream in WebKitGtk. There's now an option "Insert Emoji" in the right click menu. Closing as fixed
