### ISSUE TITLE
Print a message

### ISSUE THREAD

**Issue by danrabbit** [elementary/mail#261]
We lost the dropdown that had the print function in it

**Comment by vertexian** [comment]
Should finish with this today. I'm also adding back the per message options menu, with reply, reply all, forward, and mark read/unread commands, in addition to printing.

**Comment by marbetschar** [comment]
@danrabbit is this still relevant? I can see the "More" menu with a "Print..." option in the message header?

**Comment by cblock** [comment]
I can confirm that in v6.4.0 the dropdown exists. So I guess, this issue could be closed

**Comment by danrabbit** [comment]
Yup closing :)
