### ISSUE TITLE
Folder icon detection [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mail#262]
It looks like we don't show the proper icons for several folders. I'm not sure if this just needs to be hooked up from what EDS gives us or we need some kind of heuristic. It looks like the only one that Evolution picks up that we don't currently in "Drafts"

![screenshot from 2018-10-17 14 15 30 2x](https://user-images.githubusercontent.com/7277719/47116665-27e1f280-d217-11e8-9b24-5bd6989826ab.png)

**Comment by sivaraam** [comment]
Just wondering, what is expected as a solution for this issue?

**Comment by danrabbit** [comment]
@sivaraam That we assign the correct icons to all special folders like "Drafts", "Sent", "Starred", "Important", "Archive", etc

**Comment by Aswinpookkatt** [comment]
Is there anything else to do?
