### ISSUE TITLE
Try to fetch fallback avatars from Gravatar

### ISSUE THREAD

**Issue by danrabbit** [elementary/mail#269]
If we can't get an avatar from Folks, we should try Gravatar

**Comment by eljefuri** [comment]
@danrabbit Please tell me that this stuff is turned on optionally and that Mail isn't sending avatar requests to these services by default? Given Elementary's stance on [privacy](https://elementary.io/privacy) (always a two-way street by the way), using Gravatar/Folks seems like it should be actively discouraged in general, and certainly off by default.
