### ISSUE TITLE
Need some indication when the email is sent

### ISSUE THREAD

**Issue by rafaelcn** [elementary/mail#279]
Currently there's no way to know unless checking in the app when the email was sent. It should be a nice feature to have a sound or a notification indicating that the email was sent to the mail server.

**Comment by dracid** [comment]
I second this. Having an actual notification gives piece of mind that the message was SENT and not stuck in OUTGOING process (for whatever reason).
Thanks!

**Comment by rafaelcn** [comment]
@danrabbit that's not the common sense when a user uses some application. The user wants feedback, let the users now when the status of something has changed/updated. Although this kind of mindset can easily bloat the interface with notifications and because of that this kind of feature should be well designed. Something like Apple does on the iPhone, let the user know with some silently bar on the app or, if notification not blocked, some very brief sound should be activated.
