### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/mail#30]
The "Suggest Translation" button is pointing to the wrong link. This error has several applications.

https://translations.launchpad.net/pantheon-mail
![captura de tela de 2017-05-27 14-13-24](https://cloud.githubusercontent.com/assets/8754997/26523130/257e6a16-42e7-11e7-8c8b-d543bd1adb15.png)

**Comment by danrabbit** [comment]
Fixed in #13
