### ISSUE TITLE
Using the "Send by email" option does not respect configured applications

### ISSUE THREAD

**Issue by wout** [elementary/mail#311]
I've got Thunderbird configured as my default email client, but Files still opens Mail when using the "Send by email" option from the contextual menu:

![image](https://user-images.githubusercontent.com/107324/47619110-5e532380-dadb-11e8-854a-1a541a17e39a.png)

**Comment by danrabbit** [comment]
At the least this contact file should say "Send with Mail" to indicate that it means the Mail app instead of the generic "via Email"

**Comment by wout** [comment]
Agreed, but wouldn't it be better if the configured email client is used instead of resorting to Mail by default? Although I wish it were not, for me, Mail is unusable in its current state.

**Comment by danrabbit** [comment]
@wout I'm not sure that's possible as I don't think there is a generic API for attachments that all Mail clients follow

**Comment by wout** [comment]
@danrabbit Ok, that makes sense. But maybe the most widely used mail clients could be implemented, with a fallback to Mail if the configured option is not supported?

**Comment by danrabbit** [comment]
Since Contractor doesn't work with Flatpak, Mail doesn't provide this contract anymore. Closing since this is no longer relevant
