### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Dirli** [elementary/mail#317]
mail: current
os: gentoo
evolution-data-server-3.26.6  USE="berkdb gnome-online-accounts google gtk introspection ldap vala -gtk-doc -ipv6 -kerberos -test -weather"

FAILED: src/src@@io.elementary.mail@exe/Application.c src/src@@io.elementary.mail@exe/MainWindow.c src/src@@io.elementary.mail@exe/HeaderBar.c src/src@@io.elementary.mail@exe/Dialogs/OpenAttachmentDialog.c src/src@@io.elementary.mail@exe/Utils.c src/src@@io.elementary.mail@exe/WebView.c src/src@@io.elementary.mail@exe/WelcomeView.c src/src@@io.elementary.mail@exe/Backend/Session.c src/src@@io.elementary.mail@exe/Backend/Account.c src/src@@io.elementary.mail@exe/Backend/ContactManager.c src/src@@io.elementary.mail@exe/Composer/ComposerWidget.c src/src@@io.elementary.mail@exe/Composer/ComposerWindow.c src/src@@io.elementary.mail@exe/Composer/InlineComposer.c src/src@@io.elementary.mail@exe/FoldersView/AccountSavedState.c src/src@@io.elementary.mail@exe/FoldersView/AccountSourceItem.c src/src@@io.elementary.mail@exe/FoldersView/FoldersListView.c src/src@@io.elementary.mail@exe/FoldersView/FolderSourceItem.c src/src@@io.elementary.mail@exe/ConversationList/ConversationListBox.c src/src@@io.elementary.mail@exe/ConversationList/ConversationListItem.c src/src@@io.elementary.mail@exe/MessageList/MessageListBox.c src/src@@io.elementary.mail@exe/MessageList/MessageListItem.c src/src@@io.elementary.mail@exe/MessageList/AttachmentBar.c src/src@@io.elementary.mail@exe/MessageList/AttachmentButton.c 
/usr/bin/valac-0.36 -C --debug --pkg folks --pkg webkit2gtk-4.0 --pkg libedataserverui-1.2 --pkg libedataserver-1.2 --pkg camel-1.2 --pkg gee-0.8 --pkg granite --pkg gobject-2.0 --pkg glib-2.0 --directory src/src@@io.elementary.mail@exe --basedir ../pantheon-mail-9999/src --gresources=../pantheon-mail-9999/data/io.elementary.mail.gresource.xml ../pantheon-mail-9999/src/Application.vala ../pantheon-mail-9999/src/MainWindow.vala ../pantheon-mail-9999/src/HeaderBar.vala ../pantheon-mail-9999/src/Dialogs/OpenAttachmentDialog.vala ../pantheon-mail-9999/src/Utils.vala ../pantheon-mail-9999/src/WebView.vala ../pantheon-mail-9999/src/WelcomeView.vala ../pantheon-mail-9999/src/Backend/Session.vala ../pantheon-mail-9999/src/Backend/Account.vala ../pantheon-mail-9999/src/Backend/ContactManager.vala ../pantheon-mail-9999/src/Composer/ComposerWidget.vala ../pantheon-mail-9999/src/Composer/ComposerWindow.vala ../pantheon-mail-9999/src/Composer/InlineComposer.vala ../pantheon-mail-9999/src/FoldersView/AccountSavedState.vala ../pantheon-mail-9999/src/FoldersView/AccountSourceItem.vala ../pantheon-mail-9999/src/FoldersView/FoldersListView.vala ../pantheon-mail-9999/src/FoldersView/FolderSourceItem.vala ../pantheon-mail-9999/src/ConversationList/ConversationListBox.vala ../pantheon-mail-9999/src/ConversationList/ConversationListItem.vala ../pantheon-mail-9999/src/MessageList/MessageListBox.vala ../pantheon-mail-9999/src/MessageList/MessageListItem.vala ../pantheon-mail-9999/src/MessageList/AttachmentBar.vala ../pantheon-mail-9999/src/MessageList/AttachmentButton.vala
../pantheon-mail-9999/src/Backend/Session.vala:157.37-157.82: error: The name `util_can_use_collection_as_credential_source' does not exist in the context of `E'
        if (cred_source == null || !E.util_can_use_collection_as_credential_source (cred_source, source)) {
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../pantheon-mail-9999/src/Backend/Session.vala:148.5-148.53: error: `Mail.Backend.Session.get_oauth2_access_token_sync': no suitable method found to override
    public override bool get_oauth2_access_token_sync (Camel.Service service, out string? access_token, out int expires_in, Cancellable? cancellable = null) throws GLib.Error {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 0 warning(s)

Please, tell me where to find a solution?

**Comment by tintou** [comment]
Mail requires Evolution-Data-Server 3.28 to build and work, I just pushed a commit to make it more obvious.
