### ISSUE TITLE
Mail sidebar gets resized without my consent upon reloading the app

### ISSUE THREAD

**Issue by eljefuri** [elementary/mail#324]
I am repeating the findings from [this Photos issue](https://github.com/elementary/photos/issues/475) as they were found to be identical in Mail.

**Comment by cassidyjames** [comment]
@eljefuri is this reproducible in master? I don't believe this is an issue that is around since the rewrite, as the sizing code is much, much simpler and doing a lot less magic.

**Comment by eljefuri** [comment]
I just built master: despite apparently having connected my mail account in the online accounts switchboard, Mail doesn't seem to recognize this fact, so I cannot test it. I will mess with this more later and update my comment (perhaps filing another issue too).
