### ISSUE TITLE
No Evolution accounts recognized

### ISSUE THREAD

**Issue by HamburgerJungeJr** [elementary/mail#326]
I've installed patheon-mail from the ppa:elementary-os/stable repository on Ubuntu 18.10. 
If I run pantheon-mail --version in terminal it shows 1.0.8 so it should be the latest version.

After that I configured my EWS Account in Evolution, which can connect and show me my Emails. But in the Pantheon-Mail app there is no EWS account only my Gmail account.

**Comment by davidmhewitt** [comment]
The mail app in the stable repository is the 1.x version found in this branch: https://github.com/elementary/mail/tree/1.x

This is the version that ships in the stable version of elementary (and is the version of Mail that is based on Geary).

The code currently in `master` (and hence what the README refers to) is the startings of a rewrite of the mail client. I imagine we'll be setting up some daily builds of this version soon, but it's not feature complete or ready for production use yet.
