### ISSUE TITLE
(io.elementary.mail:29667): GLib-GIO-ERROR **: 13:50:30.115: Settings schema 'io.elementary.desktop.wingpanel.datetime' is not installed

### ISSUE THREAD

**Issue by GabMus** [elementary/mail#334]
This error leads the app to crashing when running in Arch Linux under GNOME. Installed from AUR, latest git version.

The app window shows up, but when it's about to load the emails this just happens.

I know this app is written for elementary, but I don't see why it shouldn't run on other distros/DEs.

I suppose the wingpanel functionality is to set notification indicators or something like that, it could be made optional, or the whole part of the code generating this error could be put inside a try/catch maybe?

**Comment by GabMus** [comment]
I did some research, and I got the application working when using **granite** from the fork made by [@decathrope](https://github.com/decathorpe) ([pull request here](https://github.com/elementary/granite/pull/240)).

In theory the bug is with granite more than with mail, making my issue kind of a duplicate of [this one](https://github.com/bleakgrey/tootle/issues/107).

**Comment by vitlav** [comment]
This error was introduced by https://github.com/elementary/granite/pull/222

**Comment by danrabbit** [comment]
Closing as "Out of scope" since this is an issue in Granite and not something that can be fixed in this repo
