### ISSUE TITLE
 Feature request: disable threaded/conversation view

### ISSUE THREAD

**Issue by kdekooter** [elementary/mail#35]
By default emails are grouped in threads/conversations. Deleting one mail in the thread is not possible. I would like to be able to turn this off, so display emails as separate items in the folder. And also be able to delete individual emails.

**Comment by danrabbit** [comment]
I'm going to close this as "won't fix". This is a major assumption of Mail's design. If you don't want conversations, you should use a different mail client

**Comment by kdekooter** [comment]
IMHO this is a major strategic oversight. In all of the leading email clients the threaded view is optional, letting users choose which style they want to use. A platform's "native" apps should not put users off.

**Comment by nagualcode** [comment]
what a terrible response from @danrabbit ...
Even gmail client for mobile now allow the user disables threading view. And this is a simple fix.

**Comment by BWPanda** [comment]
I don't like threading and would also like to see it made optional. But I understand if that's the decision of the Mail developers that "our app focuses on conversations, other apps exist for a more customisable experience". Fine, no worries, I can use Thunderbird for that.

But even if people do want threading/conversations, what about:

> Deleting one mail in the thread is not possible.

That's a big issue IMO, regardless of threading or not...
