### ISSUE TITLE
Pressing backspace or delete in the "To" field deletes emails

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mail#359]
Looks like it's always listening for those keypresses, even when in an input, i.e. when forwarding an email

**Comment by danrabbit** [comment]
Can confirm. It also happens in the mail message view. This is a bad one :grimacing:

**Comment by vertexian** [comment]
It seems like what we want is for the `move-to-trash` action to be available only when the message list panel (`ConversationListBox`) has focus. There's some additional logic now that's trying to disable deletion while threads load, but that seems unnecessary. The GTK event loop should ensure that loading finishes before we could process another event.

I haven't been able to figure out how to get the `focus_in_event` and `focus_out_event` signals to fire on the `ConversationListBox`. I don't understand the GTK event model well enough to know what's going wrong.
