### ISSUE TITLE
 IMAP folders should not be displayed as "Labels"  [$75]

### ISSUE THREAD

**Issue by kdekooter** [elementary/mail#36]
IMAP Folders are displayed as "Labels". While this might work for gmail accounts it violates POLA for old fashioned IMAP accounts. Moreover assigning a label to an IMAP mail does not move the mail to that label.

All in all I vouch for displaying IMAP folders as folders.

**Comment by rasmus91** [comment]
I would also give voice to this issue. Futhermore, i see it as being a problem as i am unable to delete a folder with it's content this way, or renaming them, as there is no context menu offering this for labels.

This makes using IMAP with exchange a pain.

**Comment by duch11** [comment]
As a fastmail user I very much feel the same way, are anyone working on it ATM?

**Comment by danrabbit** [comment]
This seems fixed now that we're using EDS instead of Geary Engine
