### ISSUE TITLE
Set max zoom for WebKit

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mail#363]
If I pinch-zoom in on an email, I can keep going forever which eventually makes things fail to render properly (and I believe has caused one crash, though I've been unable to reproduce that).

**Comment by cassidyjames** [comment]
In my research this is different than the `WebKit.WebView.zoom_level` property. I'm not sure where it would be constrained.

**Comment by cassidyjames** [comment]
Turns out this is an upstream issue in WebKit. https://bugs.webkit.org/show_bug.cgi?id=194865

**Comment by danrabbit** [comment]
Closing since it's out of scope
