### ISSUE TITLE
 Display forwarded indicator in IMAP mail

### ISSUE THREAD

**Issue by kdekooter** [elementary/mail#37]
Feature request: display forwarded status of an (IMAP) mail, like in Thunderbird and Mac Mail

**Comment by cassidyjames** [comment]
Could you be a little more specific, or perhaps share a screenshot pointing this feature out?

**Comment by kdekooter** [comment]
Here is a example from macOS Mail:

![image](https://user-images.githubusercontent.com/508983/27771230-d870038a-5f4a-11e7-9e54-f232e47ca4d1.png)

**Comment by danrabbit** [comment]
I think replacing the "read" indicator would probably make sense. If a message is "forwarded", it is necessarily "read".
