### ISSUE TITLE
i did uninstalled the app, now i cant reinstall.

### ISSUE THREAD

**Issue by carvajalluis** [elementary/mail#376]
Hello Guys, I uninstalled the app to try another mail clients. now that I want to give it a try again.

![image](https://user-images.githubusercontent.com/674024/54965509-77e78280-4f36-11e9-9a4e-53fd80d954f1.png)

**Comment by danrabbit** [comment]
For support questions, please see StackExchange: https://elementaryos.stackexchange.com/

Closing since this is a request for help and not an issue report

**Comment by carvajalluis** [comment]
sorry but no, it wasn't support, there was no way to reinstall the pacage  not by console or  package manager
