### ISSUE TITLE
Add a refresh button / shortcut

### ISSUE THREAD

**Issue by kdekooter** [elementary/mail#38]
It is quite unclear if and when mail polls the server. A refresh method would come in handy.

**Comment by cassidyjames** [comment]
Mail automatically frequently polls the server and shows a spinner (at the bottom-left of the window which is not the best place, but that's a different issue) when doing so. I don't believe adding a refresh button wouldn't actually make it poll any more often.

**Comment by kdekooter** [comment]
If you hook up the refresh button to the code doing the actual polling it should work.

If retrieval of mail is dependent on polling (instead of server push like with IMAP-IDLE) the user should be able control the polling by being able to configure the frequency of polling and by being able to manually trigger this.

Besides all major email clients having this feature there is a genuine use case. For instance when you signed up for a website and are waiting for the confirmation email.

**Comment by cassidyjames** [comment]
Adding configurable polling options is a separate issue with its own design considerations.

@tintou how will this work in the EDS rewrite? Can we know whether the account is push or poll based, and if it's poll-based, add a refresh action somehow?

@elementary/ux thoughts? :)

**Comment by danrabbit** [comment]
We should probably hook up to the scrollbox overshoot signal and do a pull-to-refresh

**Comment by danrabbit** [comment]
From a pure UX perspective, I like this mockup. It's very clear with the loading spinner and the toast afterwards that lets you know the operating was completed successfully:

![](https://cdn.dribbble.com/users/179112/screenshots/3427763/dribbble_-_timeline_-_v3.gif)

The use of the accent color here is really nice to look at:

![](https://cdn.dribbble.com/users/722246/screenshots/2757224/pull-down-to-refresh.gif)

iOS Mail used to also show information about when the last update was like so:

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjOF35lTyIL5xXJSIWM8C4FmxWRP4jCA1q_sZxpMxiLw8Rc4drmw)

**Comment by danirabbit** [comment]
Gonna close this since we added a refresh button
