### ISSUE TITLE
Falta a opção de *ASSINATURA.*

### ISSUE THREAD

**Issue by ojrcampos** [elementary/mail#405]
Ótimo cliente.

Porém, seria melhor se tivessa a opção de *ASSINATURA NOS EMAILS.*

**Comment by DRHAX34** [comment]
The email signature is available and configurable when you edit or add a new account to Mail.

A opção de assinatura nos emails está disponível e é configurável nas opções de edição ou de adição de conta ao Mail.

**Comment by marbetschar** [comment]
Closing this issue since Mail's code is untergoing a major rework for Odin. Feel free to open a new issue if there are any problems on elementary OS 6.
