### ISSUE TITLE
Support for SSO with Google Accounts

### ISSUE THREAD

**Issue by joedborg** [elementary/mail#408]
Currently, only Google credentials are supported.  Some enterprises authenticate via their own SSO.  An example of this working is in Gnome Online Accounts.

**Comment by danrabbit** [comment]
Closing as a duplicate of https://github.com/elementary/mail/issues/41

Mail in git master uses Evolution Data Server which can be logged into with google Oauth

**Comment by joedborg** [comment]
Thanks @danrabbit!
