### ISSUE TITLE
Window size bigger every time the application is opened

### ISSUE THREAD

**Issue by inad9300** [elementary/mail#411]
Every time I open Mail, it is bigger than before closing it, in both dimensions. It doesn't remember the closing size properly.

**Comment by danrabbit** [comment]
Thanks for your report! We're doing a from-scratch rewrite of Mail and this issue no longer applies to the new code base. I'm closing this report since the issue can't be reproduced in the new version of Mail.

**Comment by happyrobotstudio** [comment]
Cool to hear danrabbit

This issue was a non-starter for me whether using or contributing =) Looking forward to new Mail
