### ISSUE TITLE
Unable to store server trust exception

### ISSUE THREAD

**Issue by asvvvad** [elementary/mail#415]
There is a [workaround ](https://bugzilla.gnome.org/show_bug.cgi?id=736640#c27) i found after a simple search.
However in [this](https://dev.getsol.us/T7043) it is mentioned that geary 3.32 got a fix that maybe you can implement?

**Comment by reedlove** [comment]
Here is the relevant link to the Geary issue resolution:
https://gitlab.gnome.org/GNOME/gcr/-/issues/10
