### ISSUE TITLE
Make Mail a Flatpak-first application

### ISSUE THREAD

**Issue by tintou** [elementary/mail#426]
We have a chance to design an application with Flatpak in mind from day one, we should probably ship it as a Flatpak by default

**Comment by saidbakr** [comment]
I disagree. I regard that Flatpaks another fresh faulty project exactly the same like Unity. There is no any sense with downloading 1.3 GB for a package that may worth just 40 MB from the PPA. Indeed, it is a silly joke!

**Comment by danrabbit** [comment]
Gonna close this as a duplicate of #124
