### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by cleberpborges** [elementary/mail#432]
Olá, tudo bem? Escrevo para reportar bugs no aplicativo "Contas Online": esse recurso simplesmente não funciona. No Linux Mint, quando conectamos com nossa conta do Google, automaticamente esse recurso habilita o Gnome Calendar, Gnome Contacts para sincronização. Pelo que entendi, os desenvolvedores do elementaryOS não conseguiram habilitar o recurso dentro das normas de segurança exigidas por Google, Facebook e Microsoft.
Por favor, consertem isso, é muito importante que consigamos sincronizar nossas contas Google, Facebook e Microsoft com o computador.

Outro ponto importante: criem um recurso (um botão) nas configurações do sistema que possibilite habilitar/desabilitar a área de trabalho. Deixem que o usuário decidir se quer ou não a área de trabalho habilitada. 

O programa Eddy deve vir por padrão instalado no sistema. Não há lógica um usuário comum, que está chegando pela primeira vez ao elementaryOS, baixar um arquivo .deb no site da Skype e simplesmente dar dois cliques e não instalar! Resolvam isso, por favor. 

Área de notificação: outro recuso que não está presente. Novamente, poderia ter um botão nas configurações do sistema que permitiria o usuário habilitar/desabilitar, de modo bem simples. 

Dentro da App Center poderia haver uma seção destinada aos Applets para o Wingpanel. Além de facilitar a instalação de Applets úteis, como fazemos no Cinnamon, evitaria que o usuário recorresse à internet para ficar procurando soluções para a limitação do sistema.

O recurso elementary Tweaks deve ser absorvido pelo sistema com urgência, inclusive, os desenvolvedores poderiam melhorar o recurso e torná-lo ainda mais fácil de usar, nativamente.

Criem um recurso nativo para que os usuários possam escolher com facilidade o melhor driver para seu equipamento. Hoje isso é impossível com os recursos disponíveis no sistema.

A tela de login anterior era mais bonita e possibilitava uma transição mais suave para a área de trabalho. O plymouth ainda está bastante irregular, sempre aparecendo letras em fundo preto. O que interessa isso ao usuário? O macOS faz isso com muita eficiência, sigam esse exemplo. Aliás, seguir bons exemplos, como vocês já vêm fazendo - parabéns por isso!!! - só ajuda a avançar no sistema. O que não acho possível é vocês criarem um sistema bem bonito, mas que, no uso, é incompleto porque os desenvolvedores resolveram cortar vários recursos clássicos de computadores pessoais. Qual o sentido?? 

Estou me permitindo usar o elementaryOS - sou usuário avançado do Linux Mint Cinnamon - mas ainda tenho de recorrer demais ao terminal para ter o mínimo de recursos para trabalhar, coisa que o Cinnamon já resolveu faz um tempo já. 

Não coloquem a beleza acima da funcionalidade, usamos nossos computadores para produzir e trabalhar, então seus recursos precisam estar em dia com a tecnologia atual. 

Parabéns pelo elementaryOS, está muito bonito, mas ainda incompleto. Continuem com seu trabalho e espero ser convencido a permanecer nessa plataforma que me parece será uma das melhores no futuro.

Grande abraço!!

**Comment by marbetschar** [comment]
translated using DeepL.com:

> Hello, how are you? I am writing to report bugs in the "Online Accounts" application: this feature simply does not work. In Linux Mint, when we connect with our Google account, this feature automatically enables Gnome Calendar, Gnome Contacts for synchronization. As I understand it, the elementaryOS developers were unable to enable the feature within the security standards required by Google, Facebook and Microsoft.
> Please fix this, it is very important that we are able to synchronize our Google, Facebook and Microsoft accounts with the computer.
> 
> Another important point: Create a feature (a button) in the system settings that makes it possible to enable/disable the desktop. Let the user decide whether or not he/she wants the desktop enabled.
> 
> The Eddy program should come installed by default on the system. It is illogical for an average user, coming to elementaryOS for the first time, to download a .deb file from the Skype site and just double-click it and not install it! Please fix this.
> 
> Notification area: another feature that is not present. Again, there could be a button in the system settings that would allow the user to enable/disable it, very simply.
> 
> Within the App Center there could be a section for Wingpanel Applets. Besides making it easier to install useful Applets as we do in Cinnamon, it would prevent the user from searching the internet for solutions to the system limitation.
> 
> The elementary Tweaks feature should be absorbed into the system as a matter of urgency, and the developers could improve the feature and make it even easier to use natively.
> 
> Create a native feature so that users can easily choose the best driver for their equipment. Today this is impossible with the features available in the system.
> 
> The previous login screen was nicer and allowed a smoother transition to the desktop. The plymouth is still quite uneven, with letters always appearing on a black background. What does this matter to the user? macOS does it very efficiently, follow that example. By the way, following good examples, as you have been doing - congratulations on that!!! - only helps the system to move forward. What I don't think is possible is for you to create a beautiful system, but that, in use, is incomplete because the developers decided to cut several classic personal computer features. What is the point?
> 
> I am allowing myself to use elementaryOS - I am an advanced user of Linux Mint Cinnamon - but I still have to resort to the terminal too much to have a minimum of resources to work with, something that Cinnamon solved a long time ago.
> 
> Don't put beauty over functionality, we use our computers to produce and work, so your features need to be up to date with current technology.
> 
> Congratulations on elementaryOS, it looks very nice, but still incomplete. Keep up your work and I hope to be convinced to stay on this platform that I think will be one of the best in the future.
> 
> Big hug!

**Comment by marbetschar** [comment]
Thanks for your feedback! However, I have to close this issue since you are addressing a lot of different points, for a lot of different components as well as also mixing it with personal opinion. Therefore this issue is hard to act upon and cultivate an actual discussion about a specific aspect w/o having the discussion drift apart.

 Please open new issues, with one topic at a time in the repository of the corresponding component: https://github.com/elementary
You can also use the "Send Feedback" button in the elementary System Settings to guide you to the right repository:

![Screenshot from 2021-05-21 13-41-28](https://user-images.githubusercontent.com/392542/119131974-6c227880-ba3a-11eb-9374-c1056da336d4.png)
