### ISSUE TITLE
I could not able access my Gmail account

### ISSUE THREAD

**Issue by saidbakr** [elementary/mail#436]
The app always tell me that password and username are wrong. I'm sure that they are correct. Also The calendar posses the same issue with Google calendar.

```
screenfetch
                                     said@L850
         eeeeeeeeeeeeeeeee           OS: elementary OS 5.1 hera
      eeeeeeeeeeeeeeeeeeeeeee        Kernel: x86_64 Linux 5.0.0-37-generic
    eeeee  eeeeeeeeeeee   eeeee      Uptime: 14m
  eeee   eeeee       eee     eeee    Packages: 1988
 eeee   eeee          eee     eeee   Shell: bash 4.4.20
eee    eee            eee       eee  Resolution: 2806x900
eee   eee            eee        eee  DE: GNOME 
ee    eee           eeee       eeee  WM: Mutter(Gala)
ee    eee         eeeee      eeeeee  WM Theme: elementary
ee    eee       eeeee      eeeee ee  GTK Theme: Nordic-darker [GTK2/3]
eee   eeee   eeeeee      eeeee  eee  Icon Theme: Papirus
eee    eeeeeeeeee     eeeeee    eee  Font: Open Sans 9
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee   CPU: Intel Core i5-2450M @ 4x 3.1GHz [55.0°C]
  eeeeeeee eeeeeeeeeeee      eeee    GPU: AMD/ATI Thames [Radeon HD 7500M/7600M Series]
    eeeee                 eeeee      RAM: 1378MiB / 7933MiB
      eeeeeee         eeeeeee       
         eeeeeeeeeeeeeeeee          

```

**Comment by saidbakr** [comment]
I have got a security warning from Google:
```
Less secure app blocked
Google blocked the app you were trying to use because it doesn't meet our security standards.
Some apps and devices use less secure sign-in technology, which makes your account more vulnerable. You can turn off access for these apps, which we recommend, or turn on access if you want to use them despite the risks. Google will automatically turn this setting OFF if it's not being used.
```

**Comment by tintou** [comment]
See https://github.com/elementary/mail/issues/41#issuecomment-407006652 to use an application password, this is a limitation from the Google side.

**Comment by saidbakr** [comment]
> See [#41 (comment)](https://github.com/elementary/mail/issues/41#issuecomment-407006652) to use an application password, this is a limitation from the Google side.

This solution is not applicable for Google accounts that has no two steps verification! When I try the link regarded in the mentioned comment I got the following message from Google's web page:
```
The setting you are looking for is not available for your account.
```

**Comment by tintou** [comment]
So you probably need to follow the steps here https://myaccount.google.com/lesssecureapps

**Comment by saidbakr** [comment]
I don't prefer **lesssecureapps** why less?! :) The most convenient solution for the moment is using **Thunderbird**.

**Comment by zedtux** [comment]
Is there any plan to fix this issue? Why is the issue closed? For instance, Mail from macOS can connect without any issues.

**Comment by tintou** [comment]
Yes this issue will be fixed by the use of OAuthv2 that will be available in the rewrite of mail currently on-going. I'm closing comments on this issue as it starts to be off-topic
