### ISSUE TITLE
Sometimes Mail won't delete anything

### ISSUE THREAD

**Issue by maboleth** [elementary/mail#437]
Pressing the button has no effect. Not sure why that happens, but it's like there's some delay in the program itself. I can press all other buttons (there's a response), but not delete. The problem goes away after a while, but is seriously making my experience to the worse.

**Comment by maboleth** [comment]
Not only 'delete' doesn't work 100% of time, sometimes it 'resets' the window title position so it starts outside of the monitor, so I have to manually pull the window with ALT F7 in order to change the size. Sorry to say but support for Elementary OS' native apps is close to zero.

**Comment by stellr-antoine** [comment]
Same issue for me. Pressing the trash can icon doesn't seem to do anything.

Here's my folder structure.
![Screenshot from 2020-01-18 10-04-04](https://user-images.githubusercontent.com/60030806/72661477-d5bfec00-39da-11ea-99a6-5a6d44cdd836.png)

**Comment by maboleth** [comment]
Don't waste your time. Install some proper linux distro (manjaro, arch, ubuntu) or mail software (evolution, thunderbird).

**Comment by stellr-antoine** [comment]
Good things take time, my friend...
