### ISSUE TITLE
Add a unique icon

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/mail#438]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

**Describe the solution you'd like**
If I understood things correctly, Mail 2.0 will be a complete rewrite of Geary. In this context, I would like to see a unique icon that differs from Geary's icon.

**Comment by danrabbit** [comment]
The Geary folks used our Mail icon design, so I'm going to close this. If you'd like them to use a different icon design from our icon that we designed please let them know :)

**Comment by 4jNsY6fCVqZv** [comment]
Hi Daniel, thanks for getting back!

With Geary 3.32 your original app icon has already changed, so the metaphor is still the same, but the current design isn't the one you probably designed. Right now both app icons look very! similar.

see https://gitlab.gnome.org/GNOME/geary/blob/mainline/icons/hicolor/scalable/apps/org.gnome.Geary.svg

For new users, who probably do not know the development history of the two apps either, the similarity may easily lead to confusion. Which would be a pity for two completely different apps and user experiences. That's why I had the idea to suggest a new unique icon for Mail. 

And hey, I want to use Mail in the future and not Geary. That's why I ask you for change and not for more change on Geary's site ;-)

**Comment by 4jNsY6fCVqZv** [comment]
Hi Daniel, with Geary 3.32 the original app icon has already changed, so the metaphor is still the same, but the current design isn't the one you probably designed. 

https://gitlab.gnome.org/GNOME/geary/blob/mainline/icons/hicolor/scalable/apps/org.gnome.Geary.svg

Right now the icons of both apps look very similar. And that still makes sense, because you're still using Geary. But that changes for 2.0, doesn't it?

Sp for new users, who are going to get their experience with the new 2.0 version of Mail and who probably do not know the development history of the two apps either, the similarity may easily lead to confusion. Which would be a pity for two completely different apps and user experiences. That's why I had the idea to suggest a new unique icon for Mail. 

And I want to initiate the discussion here, because I want to use Mail in the future and not Geary.

If you want to stay with the current icon, I would be interested to know what argues for it from your perspective. So different from saying: "First in time, first in line."
