### ISSUE TITLE
Unable to deal with new lines in address list

### ISSUE THREAD

**Issue by trev-dev** [elementary/mail#442]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Elementary Mail can accept a list of recipients in the to/cc/bcc fields if they're comma separated, but cannot parse new lines. So if you were to copy a list of emails as such:

someone@somewhere.ca  
heyo@yo.com  
mailme@mail.com

And paste them in to any of the recipient fields, the addresses do not parse correctly. Instead, you see the addresses separated by broken unicode symbols.

If you attempt to send the mail, only the first recipient gets sent to.

### To Reproduce
1. Make/find an email list that's separated by new lines/carriage returns
2. Copy list
3. Paste into a recipients field in elementary mail
4. See the resulting list as broken.
5. Attempt to send the mail, and see that it only gets sent to the first recipient in the list.

### Expected behavior
1. Copy a list of carriage return/newline separated emails
2. Paste into any of elementary mail's recipient fields
3. See them parsed as comma-separated
4. Be able to then send the mail to all of the recipients at once.

### Screenshots or screen recordings
Not necessary

### Logs
Unsure of how to get these.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

## Additional context
Thank you!

**Comment by amz-x** [comment]
@trev-dev the end result should look similar to this, correct?

![Screenshot from 2020-01-01 21 37 47](https://user-images.githubusercontent.com/18249234/71645325-4ed2fa00-2cdf-11ea-941f-b68c23e1a9cc.png)

**Comment by trev-dev** [comment]
@amz-x That would be correct, comma separated emails that you can send a message to all the recipients with.
