### ISSUE TITLE
Emoji from Ideopedia not displayed in compose view

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#448]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

If I insert an emoji using [Ideogram](https://appcenter.elementary.io/com.github.cassidyjames.ideogram/) while writing an email, the Emoji is not displayed. The textarea just displays `[]` instead:

![Screenshot from 2020-01-12 09-20-26](https://user-images.githubusercontent.com/392542/72216132-453a6500-351d-11ea-8e65-887070d556f8.png)

### To Reproduce

1. Select an email in elementary Mail
2. Hit the "Reply" button
3. Insert an Emoji from Ideogram into the text body of the email
4. You'll see the brackets `[]`

### Expected behavior

Instead of showing the brackets `[]` of step 4 above, I'd expect the Emoji properly rendered. For example: 😂️

## Platform Information

![Screenshot from 2020-01-12 09-28-04](https://user-images.githubusercontent.com/392542/72216167-e2959900-351d-11ea-9349-3250d930c984.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by danirabbit** [comment]
![Screenshot from 2023-04-07 12 09 01](https://user-images.githubusercontent.com/7277719/230663982-7bce8b46-6541-4687-bdc5-87e4faf3e982.png)

This seems to be resolved :)
