### ISSUE TITLE
When I reply to an email, mail app shows reply twice.

### ISSUE THREAD

**Issue by drom98** [elementary/mail#465]
Hi. 
I don't know if this is a normal behaviour but I don't think so. I'm using my 365 email account in mail and when I reply to an email it sends the reply twice.
Here's an example: ![Imgur](https://i.imgur.com/CtoBZ3e.png)

**Comment by andreppi** [comment]
I assume you meant to say Office 365 from Microsoft.
If that's the case, can you check if there are any rules in the Outlook account that could be triggering that? You can find more information in this [link](https://support.office.com/en-us/article/Use-inbox-rules-in-Outlook-com-4b094371-a5d7-49bd-8b1b-4e4896a7cc5d)

**Comment by drom98** [comment]
That's not the case. And it happens also with regular outlook accounts.

**Comment by ojdorson** [comment]
I notice the same thing on my Mail using Office 365. I have checked my sent folder and my sent folder online using Outlook on the web and duplicates are not sent - in my case. The issue seems to be instead that Mail just displays the sent item twice – as in the screenshot – for some reason.

**Comment by drom98** [comment]
> I notice the same thing on my Mail using Office 365. I have checked my sent folder and my sent folder online using Outlook on the web and duplicates are not sent - in my case. The issue seems to be instead that Mail just displays the sent item twice – as in the screenshot – for some reason.
> 
> Have you checked your Sent folder live on the server at Outlook.com?

You're right. It is in fact just a visual glitch in the mail app.

**Comment by alxdrcirilo** [comment]
It also happens if you just create a new email, the sent email will be shown twice in the _Sent_ folder even though it has actually only been sent once.

**Comment by marbetschar** [comment]
@alxdrcirilo we released a fix for mails beeing stored twice in Sent for Office 365 accounts last month (https://github.com/elementary/mail/pull/625)

Can you confirm you are runnimg elementary OS 6 with the latest Mail installed?

**Comment by alxdrcirilo** [comment]
@marbetschar yes, I can confirm that. I just did a fresh install of elementary OS 6 and updated everything. The mails are still being stored twice in Sent. Bear in mind that I'm not using an Office 365 account, but a regular Outlook account instead (i.e. @outlook.com).

**Comment by marbetschar** [comment]
@alxdrcirilo what's the SMTP server's address you did configure?

Asking, because [the code](https://github.com/elementary/mail/blob/959701df5e3633b893e64282e95c03e458fd4e04/src/Backend/Session.vala#L387-L399) explicitly checks for those to see whether it needs to store an additional copy due to the fact some server types do not advertise this correctly after send (unfortunately Microsoft's server is one of them).

**Comment by alxdrcirilo** [comment]
@marbetschar I see, thanks for the explanation!

I used the following addresses:
**IMAP**: imap-mail.outlook.com
**SMTP**: smtp-mail.outlook.com

**Comment by marbetschar** [comment]
@alxdrcirilo created a fix. This will go under review and - if we are lucky - will make it into the next release of Mail 🤞

**Comment by alxdrcirilo** [comment]
@marbetschar Thank you for all your hard work!
