### ISSUE TITLE
"Super + Alt + Arrows" doesn't move the whole window

### ISSUE THREAD

**Issue by mathessaricci** [elementary/mail#489]
I don't know it's a real bug or a default, but weird, behavior. When I'm typing an email and I use "Super + Alt + Arrows" to move the mail window to another workspace the only window to move is the focused one. It'd be great that the whole thing moves together, isn't it? I took some screenshots:

![Captura de tela de 2020-06-15 21-37-04](https://user-images.githubusercontent.com/63082523/84719427-bf9a6580-af51-11ea-8266-542c10e48b7e.png)
![Captura de tela de 2020-06-15 21-37-14](https://user-images.githubusercontent.com/63082523/84719429-c1642900-af51-11ea-81d7-7f287372ddc8.png)

**Comment by danrabbit** [comment]
This has been fixed in the mail rewrite
