### ISSUE TITLE
lot of CPU used on pantheon-mail idle

### ISSUE THREAD

**Issue by abazvpo** [elementary/mail#499]
the mail app is draining my laptop's (LG GRAM 13-Z990) battery to an unusual level and this is caused by an extremely high use of CPU (even 60%)  when idle (which means a constant fan noise...heating...etc.). When I kill the process, everything starts working OK... Any ideas of how I can get it fixed?

**Comment by marbetschar** [comment]
@abazvpo is this still a concern? If yes: Which elementary OS version are you running? If you are on Hera: The code of elementary Mail is undergoing a major rework, so chances are high the original impression is no longer reflecting the current state.

Will close this for now. Feel free to reopen if the issue persists on Odin.
