### ISSUE TITLE
somehow merge the changes of upstream geary

### ISSUE THREAD

**Issue by eyelash** [elementary/mail#5]
There have been a lot of commits to the [upstream geary repo](https://git.gnome.org/browse/geary/) since the fork and maybe there could be a way to somehow merge these improvements / rebase pantheon-mail on a recent version of geary since pantheon-mail is now using git again.
Unfortunately, the git to bzr to git conversion seems to have messed up the commit hashes (e.g. compare [this](https://github.com/elementary/mail/commit/e06e13b1d300eb3dfb7a265dbc0d2e2508766858) to [this](https://git.gnome.org/browse/geary/commit/?id=e6793d6204970e882d5a8b6132a50dcc82694a9f)). Anyway, this seems to be a larger task.

**Comment by cassidyjames** [comment]
If there are more specific individual merges you'd like, I think it'd be best to file issues for those. I don't think a whole rebase is practical at this point because the codebases have diverged quite a bit.

**Comment by eyelash** [comment]
Sad to hear that. From the commit messages it looks like geary got a lot more under-the-hood fixes / engine improvements whereas pantheon-mail has a lot of UI improvements.
BTW I really like how responsive you guys are here on github and I look forward to contributing again to elementary whenever I can find the time. 😃
