### ISSUE TITLE
Unable to supply IMAP account user name

### ISSUE THREAD

**Issue by dbatsche** [elementary/mail#507]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.
- There is a similar one: #132 

## Describe the bug
On my Host & E-Mail Provider (all-inkl.com, world4you.com) I configured a few email accounts.
These email accounts have usernames instead of the actual mail address (e.g. m050a11d) but I cannot supply that one in the account settings, therefor mail is practically unusable for me.

### To Reproduce
Steps to reproduce the behavior (on elementary OS):
1. Go to 'system settings'
2. Click on 'internet accounts'
3. Click on '+ Add Account...'
4. Choose 'Email'

### Expected behavior
I expect to see a field where I supply my username.

### Screenshots or screen recordings
![620A0DA5-6EB2-4D23-AD1A-111A6F88C7AB_1_102_a](https://user-images.githubusercontent.com/6135459/94337353-19e3a180-ffea-11ea-9440-df164b36c610.jpeg)

### Logs
none

## Platform Information
- OS: elementary OS
- OS Version: 6 Odin (currently, but also on any other 'older' version)
- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version
- [x] I'm using the version on the daily build from 25th of september

## Additional context
- If this supplies more to elementary OS than mail then I'm sorry but I couldn't find a more fitting place than this one.
- If this is being refactored in a future version not currently available on the new elementary OS beta then please close this issue and I'll wait. Just wanted to raise this topic before elementary OS 6 becomes final.
- If there is already a beta to test on the next elementary OS then I'm willing to test that since I got a laptop only for the new elementary OS.

**Comment by marbetschar** [comment]
@dbatsche yes, the Online Accounts feature of Odin needs some more work. Meanwhile, you need to install Evolution and configure your Mail accounts there. After initial setup, things should start working in elementary Mail.

Keep in mind, the code of elementary Mail for Odin is undergoing a major rework right now so things may not always work as expected. Feel free to open further issues if you encounter problems.

Will close this for now.
