### ISSUE TITLE
Outlook nor gmail accounts connect to elementary mail

### ISSUE THREAD

**Issue by Devpineapple** [elementary/mail#508]
It's simple. It can't connect to my personal/work gmail account nor Outlook.

Is there a fix?

**Comment by marbetschar** [comment]
@Devpineapple try to install Evolution and configure your mail accounts there. For Google its simple, you just enter your credentials. For Outlook, you can setup an IMAP/SMTP account like I documented here: https://www.marco.betschart.name/areas/elementary-os/missing-features-and-workarounds#manage-mail-accounts

Closing this issue for now. Feel free to reopen with further information in case you need further help.
