### ISSUE TITLE
Icon display error in zh_CN environment

### ISSUE THREAD

**Issue by qy117121** [elementary/mail#515]
https://github.com/elementary/mail/blob/c52f607790d84cddcce3ec11cb9060162410133a/po/extra/zh_CN.po#L84-L86

Generate io.elementary.mail.desktop

```
Icon[uk]=internet-mail
Icon[zh_CN]=网络-邮件
Icon=internet-mail
```
Error displaying icon

**Comment by tintou** [comment]
Fixed in f57dd8276809a4ff8784b2ef53b6f681293a718b
