### ISSUE TITLE
Send email via CLI

### ISSUE THREAD

**Issue by HerrAugust** [elementary/mail#522]
Hi,

Is it possible to send emails via CLI (terminal), specifying subject, body and attachments? I imagine it is not secure, so maybe there are plugins?

For example, supposing that example@example.com is already in use in the email client, I tried the following CLI command and only got a new window opening:

`pantheon-mail mailto:example@example.com`

Thanks!

**Comment by marbetschar** [comment]
elementary Mail does not support sending emails via CLI. To do so, you want to use a specialized CLI tool such as [mstmp](https://marlam.de/msmtp/) or similar.
