### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by Adityaviganakah** [elementary/mail#543]
I am unable to sign in in my google accout

**Comment by sempasha** [comment]
@Adityaviganakah, in case you have 2-step verification turned on for your google account, you must [app password](https://support.google.com/accounts/answer/185833?hl=en)? Otherwise, please, provide more details about sign in fault.

**Comment by marbetschar** [comment]
@Adityaviganakah since there are no further details, I'm closing this. Feel free to reopen and add further information in case you still have any issues.
