### ISSUE TITLE
Move Undo Toast to the bottom

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#547]
Can we move the undo toast to the bottom of the list? It is shown whenever I delete or archive a message. I like the possibility to be able to undo a mistake, however the toast is shown quite long - and it covers the next message in line. So I feel like its blocking my workflow because I'm not sure if I need to wait for its disappearance before I should select the top most message:

![Screenshot from 2021-02-26 16-35-31](https://user-images.githubusercontent.com/392542/109321427-6c531380-7851-11eb-9dd7-28e7f05323ac.png)

**Comment by danrabbit** [comment]
I don't think it should go to the bottom. This would be inconsistent with other toasts and be really far away from tool items. But it should probably be centered to the whole window instead of this list. I agree that the current placement is kind of annoying
