### ISSUE TITLE
Sent emails are not added to "Sent" folder

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mail#550]
This might be a duplicate/related to #468, but any emails I'm sending are not being added to the Sent folder on my account as far as I can tell.

**Comment by marbetschar** [comment]
Same here: Message is not saved in Sent. This is probably just a matter of saving a copy of the mail in the Sent folder - similar to how it is implemented for saving a draft in https://github.com/elementary/mail/pull/599

And while we are at it: Error handling of sending an email can be improved. Right now it does not provide any user facing feedback if it fails and the mail is just discarded in this case. The error handling is implemented in draft saving too.
