### ISSUE TITLE
Reply button is disabled for emails coming from Garmin's ConnectIQ platform

### ISSUE THREAD

**Issue by casasfernando** [elementary/mail#557]
## What Happened
I'm using an Outlook.com account and I can't reply to emails coming from Garmin's ConnectIQ platform notifications.
The from and reply-to fields are present (and different since the from address will be noreply@garmin.com and the reply-to field will be the actual user address where the reply needs to go).
The forward button is enabled, but the the reply and reply-all buttons are disabled. To workaround this I need to reply to these emails by using Outlook.com web interface which is really annoying.
I can share a source message if that will help to troubleshoot this issue as it is very specific to the this email type.

## Expected Behavior
The reply button is enabled and by clicking on it a new compose message window is created with the To field set to the reply-to field value of the original email.

## Steps to Reproduce

1. Select and email from Garmin Connect IQ Team user feedback notifications (I can provide a source message for troubleshooting)
2. Try to reply to this message.

## Platform Information
elementary OS 5.1.7 Hera with latest updates as of 1st of April 2021.
pantheon-mail/bionic,now 1.0.8+r2496+pkg18~ubuntu5.0.1

**Comment by casasfernando** [comment]
Not sure if it can be somehow related to https://github.com/elementary/mail/issues/398.

**Comment by cassidyjames** [comment]
Without looking at the code, I bet we're just not handling the case where the reply address is noreply while the reply-to is something else.

**Comment by casasfernando** [comment]
I can share a message source if needed for analysis or troubleshooting. Just let me know.
In case it may help this is how one of these messages headers look like (obfuscated some values for the sake of privacy):
```
Date: Sat, 13 Mar 2021 22:59:08 +0000
From: <noreply@garmin.com>
Reply-To: <someuser@example.com>
To: <myemailaddress@outlook.com>
Message-ID: <XXXX753479.XXX.1615676348002.JavaMail.vcap@XXXXXXXX-8be6-4199-XXXX-0830>
Subject: User Feedback for CIQApp - Connect IQ Notification
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
```

**Comment by casasfernando** [comment]
I just found that this problem was fixed at some point (not sure when tough).
I'm running Mail version `io.elementary.mail/focal,now 6.1.1+r701+pkg24~ubuntu6.1` on elementary OS 6 Odin.

Feel free to close the issue.
Thanks!

**Comment by marbetschar** [comment]
Closing for now. Feel free to re-open when needed.
