### ISSUE TITLE
iCloud IMAP not syncing with new Mail App.

### ISSUE THREAD

**Issue by tofutech** [elementary/mail#562]
## What Happened
Tried to resync my iCloud email address with the new mail app after moving to the 6.0 Early Access, the information takes successfully, but trying to reopen Mail it still shows no connected accounts. 

## Expected Behavior
iCloud should sync just fine. It syncs in the old Mail app and in Evolution.

## Steps to Reproduce
1. Open Mail
2. Sign Into iCloud

## Platform Information
Elementary OS 6.0 4/13/2021 Daily

**Comment by cassidyjames** [comment]
How are you signing into iCloud? Mail doesn't have a built-in sign in flow.

**Comment by tofutech** [comment]
> How are you signing into iCloud? Mail doesn't have a built-in sign in flow.

When opening Mail it gives an option to add an Online Account, taking me to the Online Accounts page in settings. It says everything is entered correctly but the account never shows up in Mail.

**Comment by cassidyjames** [comment]
Ah yeah, gotcha. See the README for more info:

https://github.com/elementary/mail#connecting-your-account

For now, you'll need to install Evolution from the Ubuntu repos (`sudo apt install evolution`) and set up your account there, then it will show up in Mail; the connection from Online Accounts to EDS is not complete.

**Comment by tofutech** [comment]
Would I have to download the version from apt? I'm not home to test but I tried using the flatpak to do so last night and no go.

**Comment by cassidyjames** [comment]
@tofutech yeah I believe it has to be the one from apt so it sets up the system-accessible copy of EDS as opposed to a sandboxed version.

**Comment by tofutech** [comment]
Gotcha, yeah that makes sense. Thank you so much. Keep up the good work.

**Comment by PoweredByTea** [comment]
I also noticed Mail would not connect to Apple's iCloud servers when following the instructions listed in https://support.apple.com/en-us/HT202304 . 

I noticed this issue started to occur after a recent outage Apple reported on o4/19/2021 and of/20/2021:

"iCloud Mail - 2 Resolved Issues

Yesterday, 10:06 AM - 1:42 PM

Some users were affected

Users may have been unable to send or receive mail.

Today, 8:06 AM - 10:58 AM

Some users were affected

Users may have been unable to send or receive mail."

According to the GNOME Evolution website, there may have been a change by Apple that is now affecting Evolution.

This may be reviewed here: https://gitlab.gnome.org/GNOME/evolution/-/issues/1468
