### ISSUE TITLE
Unified Inbox

### ISSUE THREAD

**Issue by remalhaut** [elementary/mail#570]
## Problem
The updated Mail app has gained better mail account support by using the Evolution Data Server, but no longer has unified inboxes for multiple accounts.

## Proposal
If feasible, please add back the unified inbox.

## Prior Art
Previous versions of Mail and Geary automatically integrate multiple accounts' inboxes into one unified folder.

**Comment by marbetschar** [comment]
This is already in the works an will be fixed by #564

**Comment by marbetschar** [comment]
Closing as duplicate of https://github.com/elementary/mail/issues/449.
