### ISSUE TITLE
Certain Mails are not rendered

### ISSUE THREAD

**Issue by candiedoperation** [elementary/mail#582]
## What Happened

Certain Emails are not rendered (displayed) in elementary Mail (elementary OS Odin). These _certain mails_ which are not rendered are visible when the reply button is clicked on the mail. I feel there is some problem in the code which displays mail and not the email because, the email is correctly visible when the reply button is clicked.

## Expected Behavior

The normal way mails are displayed is the behavior expected from elementary Mail.

## Steps to Reproduce

There are no steps to reproduce. Certain Mails are not displayed.

Adding a few screenshots below to best describe the issue:

Mail 1 (Displayed Properly)**
![02](https://user-images.githubusercontent.com/47198395/119247810-6186f100-bbaa-11eb-8369-c91c7dea7754.png)

Mail 2 (Not displayed properly)**
![01-same](https://user-images.githubusercontent.com/47198395/119247819-6c418600-bbaa-11eb-9b20-829dbe42eb09.png)

Mail 2 (The same email, when the reply button is clicked)**
![01](https://user-images.githubusercontent.com/47198395/119247830-81b6b000-bbaa-11eb-9b8f-e2322cc3d05e.png)

****Text has been blurred for privacy concerns**

### Logs

No Logs

## Platform Information

Operating System: elementary OS 6
Edition: (Public Beta)
Hardware Information:
- Quad-Core Intel® Core™ i5-8250U CPU @ 1.60GHz
- Intel® UHD Graphics 620 (Kabylake GT2)
- 7.7 GiB memory
- 467.2 GB storage (SSD)

Laptop Information: HP Pavilion x360

**Comment by matfantinel** [comment]
I have a single email message with the same problem. It is not sensitive information, so I can try forwarding it if someone is having trouble to reproduce.

**Comment by stan-janssen** [comment]
I am encountering this problem too. I tried debugging the application to see if anything obvious stands out, but not so far.

```bash
$ G_MESSAGES_DEBUG=all gdb io.elementary.mail
````

Scenario 1: opening a message that renders correctly:

```
[New Thread 0x7fffc37fe700 (LWP 22889)]

(io.elementary.mail:22730): Handy-WARNING **: 21:52:21.717: Failed to load icon: Not Found
** (io.elementary.mail:22730): DEBUG: 21:52:21.717: MessageListItem.vala:478: Opening message
[Thread 0x7fffc0ff9700 (LWP 22871) exited]
(io.elementary.mail:22730): GLib-DEBUG: 21:52:21.730: posix_spawn avoided (child_setup specified) 
[Detaching after fork from child process 22890]
[New Thread 0x7fffc0ff9700 (LWP 22891)]
(WebKitWebProcess:2): GVFS-RemoteVolumeMonitor-DEBUG: 21:52:21.767: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(WebKitWebProcess:2): GVFS-DEBUG: 21:52:21.769: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(WebKitWebProcess:2): GLib-GIO-DEBUG: 21:52:21.769: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[Thread 0x7fffc37fe700 (LWP 22889) exited]

```

Scenario 2: opening a message that does not render correctly:

```
[New Thread 0x7fffc37fe700 (LWP 22908)]

(io.elementary.mail:22730): Handy-WARNING **: 21:52:30.565: Failed to load icon: Not Found
** (io.elementary.mail:22730): DEBUG: 21:52:30.565: MessageListItem.vala:478: Opening message
[Thread 0x7fffc0ff9700 (LWP 22891) exited]
(io.elementary.mail:22730): GLib-DEBUG: 21:52:30.574: posix_spawn avoided (child_setup specified) 
[Detaching after fork from child process 22909]
[New Thread 0x7fffc0ff9700 (LWP 22910)]
(WebKitWebProcess:2): GVFS-RemoteVolumeMonitor-DEBUG: 21:52:30.609: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

(WebKitWebProcess:2): GVFS-DEBUG: 21:52:30.611: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(WebKitWebProcess:2): GLib-GIO-DEBUG: 21:52:30.611: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[Thread 0x7fffc37fe700 (LWP 22908) exited]

```

These two scenarios look identical to me, so not much to learn from this first look.

(I added the debug line in line 478 "Opening Message" myself to verify that this is the codepath that gets executed when selecting a message).

**Comment by marbetschar** [comment]
Ok; so I tracked this down. The root cause relies in `WebKit` itself, since it does not seem to be able to report the correct page sizes for each mail. Therefore [this code](https://github.com/elementary/mail/blob/a5da1599732088b42a0abd7ebfd30df6f76a373e/src/WebView.vala#L92-L104) sometimes sets the wrong widget height - and therefore the mail seems not to be rendered.

The thing I'm struggling now with is, that I do have several mails causing `get-page-height` to behave differently: For mails sent by PayPal, it returns a wrong height of 1px. However, for other test cases on my end it returns a wrong height of 33px .... so it seems to be rather hard to define which heights are wrong.

@davidmhewitt any ideas?
