### ISSUE TITLE
Accounts Don't Log In On Beta 6.0

### ISSUE THREAD

**Issue by TobyMaddix** [elementary/mail#583]
## What Happened
After logging in to an email from settings -> online accounts, the account won't appear in the mail app.

## Expected Behavior
It should log into the account.

## Steps to Reproduce
Try to log into an account and it will not work.

## Platform Information
Elementary OS 6.0 latest release.

**Comment by candiedoperation** [comment]
@TobyMaddix, in the repository page https://github.com/elementary/mail it is clearly mentioned:

# Connecting Your Account
Mail uses Evolution Data Server and Camel to display your emails. Currently, the **easiest way to test Mail with your accounts is to set up them up in Evolution first**. Ultimately, **setting up an account in Online Accounts** will connect it to EDS/Camel but that has **not yet been implemented**.

**Comment by shawn1thompson** [comment]
Daniel mentioned in the last Q&A video that Online Accounts is fixed. I'm guessing this doesn't necessarily mean that Mail is.

**Comment by danrabbit** [comment]
The Online Accounts rewrite is now building in Daily, so this can be considered as "Fixed"
