### ISSUE TITLE
Use mark_seen_timeout from E.Source

### ISSUE THREAD

**Issue by danrabbit** [elementary/mail#584]
## What Happened

We've currently hardcoded the timeout for marking a mail as read, but there is a property https://valadoc.org/libedataserver-1.2/E.SourceMailAccount.mark_seen_timeout.html

**Comment by davidmhewitt** [comment]
AFAIK this is just a property read from evolution's dconf namespace. Hopefully it works without evolution installed, but we may want it to be independent anyway?

**Comment by danrabbit** [comment]
Ah nevermind then 😅

**Comment by tintou** [comment]
@davidmhewitt It's not read from dconf, it's just a property per account or folder
