### ISSUE TITLE
No folders, emails, etc.

### ISSUE THREAD

**Issue by shawn1thompson** [elementary/mail#596]
## What Happened

I've successfully added my IMAP account to Online Accounts, but nothing shows up in Mail at all. It doesn't prompt for an account though and the account is listed when I go to Account Settings from Mail.

## Expected Behavior

Emails and folders should load.

## Steps to Reproduce

1. Add IMAP account to Online Accounts
2. Open Mail

### Logs

Not sure which logs to grab, but would be happy to.

## Platform Information

Odin Beta 2 (fresh install)

**Comment by marbetschar** [comment]
@shawn1thompson which Mail provider are you using?

You probably need to make extra sure, you spelled the password correct. It is not verified at the moment in the account creation process (somethimg we need to improve).

Also, please make sure whether you need an application specific password or not (depends on the mail provider if you can use your regular user password, or generate an extra one).

**Comment by shawn1thompson** [comment]
I'm using Proton Mail with their Bridge application. The password is simply copied and pasted from said application.

**Comment by shawn1thompson** [comment]
No longer using Elementary of Proton and will be unable to troubleshoot if needed.
