### ISSUE TITLE
Cannot build from sources

### ISSUE THREAD

**Issue by mbrennwa** [elementary/mail#611]
## What Happened
I downloaded the current source code from github, installed the depencies as described at https://github.com/elementary/mail#building-testing-and-installation, and then tried to compile/build Mail by executing `meson build`.

The build failed with the following error:

```
Dependency granite found: NO found 5.5.0 but need: '>= 6.0.0'
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency granite found: NO 

meson.build:10:0: ERROR: Invalid version of dependency, need 'granite' ['>= 6.0.0'] found '5.5.0'.
```
This was all done on my Debian machine (Debian SID/unstable). `libgranite-dev` is version 5.5, which is fine according to the build instructions saying version 5.2 or newer is required.

## Expected Behavior
I expected the build to succeed as described in the instructions.

## Platform Information
Debian SID/unstable

**Comment by ryonakano** [comment]
Seems like README stays old, we need granite >= 6.0.0 to build the latest Mail
