### ISSUE TITLE
Don't attempt to save draft if empty

### ISSUE THREAD

**Issue by kdwk** [elementary/mail#619]
## What Happened

https://user-images.githubusercontent.com/39268094/126264023-14ce084f-d010-4ada-8fa4-92a083cfdd97.mp4

Mail attempts to save the draft even when there is nothing in the draft

## Expected Behavior

If there is nothing in the email yet, don't try to save it as a draft

## Steps to Reproduce

1. Compose mail
2. Don't add anything
3. Close the compose mail window
4. It will try to save it to drafts

## Platform Information

![Screenshot from 2021-07-14 10-55-34](https://user-images.githubusercontent.com/39268094/126264186-0eb230a3-a154-46de-b628-190465833879.png)

Mail 6.0.0

**Comment by marbetschar** [comment]
@davidmhewitt are you aware of an easy way to detect changes in the composer or the webview after initial load?
