### ISSUE TITLE
Can't add a Gmail account

### ISSUE THREAD

**Issue by Mihail-Bogdanov** [elementary/mail#632]
As specified in the title i cannot add a Gmail account. I just installed the system and opened the mail app for the first time so there are no steps to reproduce.
I chose "Gmail" as "Service"; typed my gmail address and password **correctly** but when clicking "Add" the welcome screen gives me this error: "_Unable to validate: Username or password incorrect_".
Also, I have two factor authentication enabled in my gmail.

**Comment by danrabbit** [comment]
Gmail requires app specific passwords for use with IMAP. Have you configured an app password in your Gmail settings and made sure that you have IMAP login turned on?

**Comment by Mihail-Bogdanov** [comment]
@danrabbit Yes, It is enabled since I can log in with tunderbird

**Comment by Mihail-Bogdanov** [comment]
I went to my gmail account and created a specific app password and I could log in.
but or some reason I can login in thunderbird just fine with two-factor authentication.
