### ISSUE TITLE
Not getting new email notifications

### ISSUE THREAD

**Issue by matfantinel** [elementary/mail#635]
## What Happened
On elementary OS 6.0, I'm not getting notifications for new mail. I setup my Fastmail account via IMAP on System Settings, but I am not getting new mail notifications via the Mail app. I've tried different situations, and did not get a notification on any of them:

* After a clean boot, without opening the Mail app (no notifications)
* After opening the app once, then closing it (no notifications)
* With the app open, but not focused (no notifications)

Not sure if intended, but I don't see any process for io.elementary.mail running in the background when it's closed, like there was on 1.0.

Notifications are enabled for the app on System Settings: 
![image](https://user-images.githubusercontent.com/24247035/128934586-fe389ffd-4531-421e-a6e4-f2a50015dbc1.png)

## Expected Behavior
Mail app should display notifications for new mail.

## Steps to Reproduce

1. Setup an IMAP account via the "Online Accounts" panel in System Settings
2. Receive emails
3. No notifications will be displayed

### Logs
Not sure how to grab logs for this, but these are the Evolution-related processes running on my machine. Not sure if any of them is related to fetching emails or not.
![image](https://user-images.githubusercontent.com/24247035/128935080-5b4cb330-1a9a-493f-bb14-4df53971f581.png)

## Platform Information

* elementary OS 6.0 Odin (RC3 with all updates installed)
* Linux 5.11.0-25 generic
* Dell XPS 9570

**Comment by RajSolai** [comment]
Me too experiencing the same issue with Gmail - IMAP , also there is no option for "Always watch for new email"

**Comment by rasmus91** [comment]
Same here. When you try to go to settings, you are sent to online accounts, where you can't really change anything pertaining to mail.

**Comment by danrabbit** [comment]
Please don't make "me too" comments. You can use the :+1: reaction in the issue report to indicate that the issue affects you as well. Making "me too" comments makes it harder to find comments with helpful information
