### ISSUE TITLE
Mail registering itself as default Image Viewer

### ISSUE THREAD

**Issue by matfantinel** [elementary/mail#637]
## What Happened
On elementary OS 6.0, when I open the Mail app, it automatically registers itself as the default image viewer. See screenshots below.

Before opening Mail:
![image](https://user-images.githubusercontent.com/24247035/128935521-f1adefb7-caad-48a8-abbb-63b7b78d2472.png)

After opening Mail:
![image](https://user-images.githubusercontent.com/24247035/128935537-22b7708b-23da-4c33-97aa-da1029ec4cce.png)

I also caught it registering itself as the default web browser (!), and PDF viewer as well, however I could not reproduce it again after resetting the options to the correct ones. However, Mail still remains an option of default web browser in the Applications -> Defaults panel shown above.

## Expected Behavior
Mail shouldn't mess with default application settings, nor register itself as an image viewer/web browser.

## Steps to Reproduce

1. Open the Mail app
2. Try to open any image from Files
3. Mail will open instead of Image Viewer (it doesnt load the image)
4. Checking System Settings -> Applications -> Defaults shows Mail is registered as default Image Viewer

## Platform Information

* elementary OS 6.0 Odin (RC3 with all updates installed)
* Linux 5.11.0-25 generic
* Dell XPS 9570

**Comment by marbetschar** [comment]
That's a weird one. Never came across this on my machine. Does this happen for you as well on a fresh elementary OS 6 stable install?

**Comment by matfantinel** [comment]
@marbetschar i haven't tried a clean install from stable yet, as I'm trying to avoid reinstalling everything from scratch again. But I only noticed this behavior after the latest batch of updates, and not right after the installation.

**Comment by matfantinel** [comment]
Hmmm, this might not be Mail's fault. After booting today I say that the Image Viewer app registered itself as the default Mail app...

![image](https://user-images.githubusercontent.com/24247035/129037741-fe0a9654-f383-4fa3-8e71-b6ba88fa6783.png)

**Comment by matfantinel** [comment]
Yeah this is not caused by Mail, my default apps situation is really messy here. I'm gonna close this, investigate a bit further and open an issue on switchboard maybe
