### ISSUE TITLE
Change email account settings

### ISSUE THREAD

**Issue by dev-pedro** [elementary/mail#638]
## What Happened

Once the email account is added and configured, it is not possible to change the account settings.

## Platform Information

OS: elementary OS 6 Odin x86_64
Host: X555UB 1.0
Kernel: 5.11.0-25-generic
Shell: bash 5.0.17
Resolution: 1366x768
DE: Pantheon
WM: Mutter(Gala)
Theme: io.elementary.stylesheet.lime [GTK3]
Icons: elementary [GTK3]
CPU: Intel i7-6500U (4) @ 3.100GHz
GPU: Intel Skylake GT2 [HD Graphics 520]
GPU: NVIDIA GeForce 940M
Memory: 2345MiB / 7858MiB

**Comment by marbetschar** [comment]
This is more of an issue for the Online Accounts plug in the System Settings. I opened a corresponding issue here: https://github.com/elementary/switchboard-plug-onlineaccounts/issues/201

But we can keep this issue around till its fixed - its probably helpful for others as well.

**Comment by dcowan-london** [comment]
Also means there’s no way to set a signature. https://github.com/elementary/mail/issues/616

**Comment by marbetschar** [comment]
Closing this because this will be possible in the upcoming update of System Settings > Online Accounts.
