### ISSUE TITLE
When deleting mail via delete key, the next message does not get automatically selected - Quick delete not possible

### ISSUE THREAD

**Issue by Schykle** [elementary/mail#641]
## What Happened

When selecting an email in the list of messages, pressing `Delete` will delete the message, but the next message in the inbox/list does not get selected, which means `Delete` cannot be pressed again to just delete the following message, and so on.

## Expected Behavior

When `Delete` is pressed, the message should get trashed/deleted, and the next message in the inbox should be selected/active to allow the user to act on it.

## Steps to Reproduce

1. Select an email in the inbox
2. Press `Delete`
3. Attempt to delete again for the next message without use of mouse

## Platform Information

elementary OS 6.0 Odin - Fully updated as of 08/12/2021 05:00

**Comment by casasfernando** [comment]
I would love to see this behavior changed as described by @Schykle.
I have some folders with daily reports that I just need to quickly review and delete. With the current behavior this process is very tedious and needs to use pointer + keyboard which is not ideal.

Thanks!

**Comment by gfavaro** [comment]
I am facing the same issue in elementary OS 6.1 Jólnir
