### ISSUE TITLE
Untranslated strings in the submenu

### ISSUE THREAD

**Issue by roxfr** [elementary/mail#645]
Hi,

There are two untranslated strings in the submenu (left click) of the create new message window.
- Paste As Plain Text
- Insert Emoji

See framed in red on the image below:

![E-Mail_01](https://user-images.githubusercontent.com/52124613/129459924-6d0d2c28-3a3e-44e4-a907-218286de06a2.jpg)

Regards,
Roxfr

**Comment by ryonakano** [comment]
We use WebView in Webkit for the text view here. You can translate these strings in https://l10n.gnome.org/module/webkit

**Comment by roxfr** [comment]
> We use WebView in Webkit for the text view here. You can translate these strings in https://l10n.gnome.org/module/webkit

Ok I'll go check it out!
Thank you.
Regards,
Roxfr

**Comment by roxfr** [comment]
@ryonakano
I created a bug report (translation) for webkit.
Hope this is dealt with quickly.
[https://bugs.webkit.org/show_bug.cgi?id=229119](url)

**Comment by ryonakano** [comment]
You should register to GNOME Dammed Lies and upload your translation file instead :)

**Comment by roxfr** [comment]
> You should register to GNOME Dammed Lies and upload your translation file instead :)

Okay that's good !
I completely translated the "webkit.HEAD" into French as a result (see the link).
Thank you.
@+ Roxfr

[Link](https://l10n.gnome.org/vertimus/webkit/HEAD/webkit/fr/)
