### ISSUE TITLE
email replies are sent from the wrong email account (and always from the same one)

### ISSUE THREAD

**Issue by casasfernando** [elementary/mail#658]
## What Happened
I have two email accounts in Mail. One for Outlook.com and another one for Gmail.com.
If I reply to an email that I received in my Outlook.com account, the reply will be wrongly sent from my Gmail.com account instead.
If I reply to an email that I received in my Gmail.com account, the reply will be correctly sent from my Gmail.com account.
In summary it seems that all email replies are being sent from my Gmail.com no matter the email account the mail was received on.
This issue is kind of sensitive since it may disclose one of your email accounts to an undesired recipient.

## Expected Behavior
email replies should be sent from the the same email account the email replied to was received.
Ideally the email address from where the reply will be sent should be displayed in the UX (From field) and even perhaps allow the user to select the account to send the reply from.

## Steps to Reproduce

1. Configure two different email accounts in Mail (ideally from two different email providers).
2. Select and email from your Inbox and click the reply button.
3. Type the email reply and click on the send button.
4. Check both accounts "Sent" folder to confirm from where the email was sent.

### Logs
N/A

## Platform Information
elementary OS 6 (Odin)
Mail version: io.elementary.mail/focal,now 6.1.0+r613+pkg23~ubuntu6.1

**Comment by marbetschar** [comment]
This has already been fixed in https://github.com/elementary/mail/pull/634 - waiting for code review there.

**Comment by casasfernando** [comment]
Awesome news. I hope it will be merged and released soon because for my use case I’m being forced to use Geary in the meantime. :(

**Comment by marbetschar** [comment]
Same here ;)

**Comment by marbetschar** [comment]
Closing since the fix has been merged and released.
