### ISSUE TITLE
Reply To: Sender account wrong if recipient is not identical

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#671]
## What Happened

While https://github.com/elementary/mail/pull/634 introduced a fix for pre-selecting the correct account when replying to an e-Mail, there is still room for improvement: It does not work correctly in cases where the recipient address does not match 1:1 with any configured mailbox account.

Some examples:

- The following recipient addresses are all delivered to the same Gmail inbox:
    - xyz@gmail.com
    - xyz+abc@gmail.com
    - xyz+def@gmail.com
    - xyz+...@gmail.com
- There are other providers, allowing similar things
- Also, if the user configured a CATCH ALL address on his `custom-domain.tld`, it is also possible to forward `anything@custom-domain.tld` to a specific inbox like `my-inbox@custom-domain.tld`

## Expected Behavior

When I reply to a mail which was sent to `xyz+test@gmail.com`, I'd expect the account to send the reply from which is selected to be `xyz@gmail.com`. Similarly, if the mail was sent to `test-abc@custom-domain.tld`, I'd expect `my-inbox@custom-domain.tld` to be preselected.

## Proposed Solution

If there is no exact match, we should test for the mail address domain `@domain.tld`. If there is more than one match with the same domain, we should check if the local part of the address `xyz+abc` contains the prefix of a known mail account's local part within the same domain.

**Comment by 4jNsY6fCVqZv** [comment]
> Similarly, if the mail was sent to test-abc@custom-domain.tld, I'd expect my-inbox@custom-domain.tld to be preselected.

If the email was sent to `test-abc@custom-domain.tld`, I would expect a reply to automatically pre-select `test-abc@custom-domain.tld` as the sender.

**Comment by marbetschar** [comment]
@4jNsY6fCVqZv sure 😆 - but only in case this mail account exists. In the scenario described above, the original recipient of the mail was `test-abc@custom-domain.tld` - but this mail box does not exists, therefore the CATCH ALL rule on the server forwarded it to the `my-inbox@custom-domain.tld` account. And the `my-inbox@custom-domain.tld` is also the account configured in elementary Mail.

**Comment by marbetschar** [comment]
Looked at it again and now it behaves correctly since the code in place uses the account mail address for comparison. I probably selected another From address during scrolling, because the conversation is rendered above - but that's one for another issue.
