### ISSUE TITLE
System folders are sorted in alphabetical order

### ISSUE THREAD

**Issue by AI-ien** [elementary/mail#673]
I'm using outlook.com and built in folders are sorted in alphabetical order together with personal folders. 

System folders are expected to be on top in following order (preferably):
* Inbox
* Junk mail
* Drafts
* Sent items
* Snoozed
* Deleted items
* Archives
--
*  Personal folders

Currently only Inbox folder is on top, hopefully.

**Comment by cassidyjames** [comment]
I agree it makes sense to sort most special folders to the top, but I wonder if Archive/Trash should be sorted to the bottom?

**Comment by AI-ien** [comment]
> I agree it makes sense to sort most special folders to the top, but I wonder if Archive/Trash should be sorted to the bottom?

Well, that's up to debate. I just took example of how Microsoft sorts it. Gmail for example has slightly different order. Most importantly is that those are placed above personal folders.

**Comment by leolost2605** [comment]
Closing as fixed with #910
