### ISSUE TITLE
Add support to manually refresh mail account (and show activity indicator)

### ISSUE THREAD

**Issue by marcelovbcfilho** [elementary/mail#675]
## Problem

I would like to have some kind of feedback from when I select to refresh, or when the app is automatically refreshing the inbox mails, because now we aren't able to say if the inbox is refreshing or we just doesn't have any new inbox mails.

## Proposal

My proposal is to add a new icon beside the account e-mail to work like a shortcut to force refreshing the emails and when the button is pressed, just to give a visual feedback the emails part of the app becomes empty with a loading icon at the middle.
Because I think that the biggest barrier is the missing of a visual feedback.

## Prior Art

Image 1: Display a place where a button of refresh should appear for an easier to find it. 
![Screenshot from 2021-08-31 18-54-56](https://user-images.githubusercontent.com/51462138/131581619-b34374d5-13a8-4e92-8a96-e4a330706237.png)

Image 2: How after clicking the button the app should behave, just a loading icon moving.
![Screenshot from 2021-08-31 18-54-562](https://user-images.githubusercontent.com/51462138/131582352-17a57344-2fcd-4042-b962-b4dc08686679.png)

**Comment by marbetschar** [comment]
Hi @marcelovbcfilho 👋,

Thanks for the bug report! This is definitely on our plate to work on - and there is already an issue for providing an activity indicator: https://github.com/elementary/mail/issues/288

However, it seems you also want a way to manually trigger a refresh. Therefore I rename this issue to reflect this additional feature request.

**Comment by marbetschar** [comment]
Closing because "Manual refresh" has been added in https://github.com/elementary/mail/pull/680
