### ISSUE TITLE
Mail crashes immediately after start

### ISSUE THREAD

**Issue by frank-wo** [elementary/mail#677]
## What Happened
Mail Clients crashes immediately after start. 
It worked the last 9 months without this problem.

## Steps to Reproduce

1. Click on the Icon and start the app

### Logs
No Idea, how to get it. Sorry, I'm using Elementory because I have no idea from Linux internals. Followed instructions and tried 
"G_MESSAGES_DEBUG=all io.elementary.mail"
from a terminal, but it didn't work (io.elementary.mail: Unknown command.).

## Platform Information
Elementory OS  5.1.7 Hera
Mail 1.08 - 15. Okt. 2018

**Comment by marbetschar** [comment]
Hi @frank-wo 👋,

Sorry to hear you ran into troubles! I can't tell what caused elementary Mail to crash on your end as it has been entirely rewritten for elementary OS 6. Therefore you might want to consider upgrading to elementary OS 6: https://elementary.io/

If you can't upgrade immediately, you might want to use another Mail client such as [Geary](https://wiki.gnome.org/Apps/Geary) or [Evolution](https://wiki.gnome.org/Apps/Evolution/) in the meantime. I'm sorry for the inconvienience!

I'm closing this for now, but feel free to open new issues if you run into troubles on OS 6 - we are happy to help!
