### ISSUE TITLE
GLib-GIO-ERROR **: Settings schema 'org.pantheon.mail' is not installed

### ISSUE THREAD

**Issue by dlukes** [elementary/mail#7]
I'm experimenting with Pantheon Mail on Arch Linux and it builds fine, but when I try to run it, I get the following error (as you can see, I've installed under `~/.local`):

```
 [msg] 16:24:16 0.033378 geary-application.vala:204: Mail 1.0.5 prefix=/home/david/.local exec_dir=/home/david/.local/bin is_installed=true

(pantheon-mail:17550): GLib-GIO-ERROR **: Settings schema 'org.pantheon.mail' is not installed

[1]    17550 trace trap (core dumped)  pantheon-mail -d
```

Did I perhaps miss a runtime dependency? Thanks for any pointers!

**Comment by tintou** [comment]
It's not a runtime dependency but GSettings searches for schemas in the directories listed on the `XDG_DATA_DIRS` environment variable, this is the case for any application using GSettings.
Reopen the issue if you still encounter an issue afterward

**Comment by dlukes** [comment]
Oh of course, right you are, thanks very much for the swift reply!
