### ISSUE TITLE
Include Attachments when Forwarding an E-Mail

### ISSUE THREAD

**Issue by marbetschar** [elementary/mail#729]
### Problem

When we forward an email with attachments, the attachments does not seem to be attached in the forwarded mail. While this is reasonable if we reply to an email, I think it would be better to append the attachment when we forward.

### Proposal

If the user forwards an email with attachments, also append the attachments to the forwarded mail.

**Comment by janxkoci** [comment]
What exactly is needed in terms of design? Both the old Mail and Geary had this basic functionality for years and it worked well.

**Comment by danirabbit** [comment]
Probably doesn't need design, the tag is automatically added in the feature request template. I'm sure it just needs someone to implement it :)
