### ISSUE TITLE
Unified Inbox Not Working With EWS Office365

### ISSUE THREAD

**Issue by keithcdodd** [elementary/mail#737]
### What Happened?

Elementary OS6 Odin, Pantheon Mail. OAUTH2 Office365 and Gmail accounts. Could not figure out a way to add those accounts in the normal online accounts method given OAUTH2 (throws error saying need to be online), but worked around it by downloading Evolution .deb and adding accounts there for both the gmail and the office365 (office 365 was set up through ews). Note for anyone this might help, doing this with Evolution flatpak does not work, needs to be .deb.

Gmail and office365 accounts now show as non-editable online accounts and appear in the pantheon mail app. However, while the gmail shows in the unified inbox, the office365 does not. I can confirm that the office365 is the issue, as I can also add my personal outlook account through the regular online account means in EOS6 and that too populates the unified inbox. Only the office365 through EWS does not appear.

I do not know if this is specifically a thing just for office365, or for all exchange accounts added through EWS protocol through evolution.

Thanks!

### Steps to Reproduce

1. Need to add email accounts with OAUTH2
2. Download .deb of Evolution
3. Add accounts through Evolution, including Office365 OAUTH2 through EWS
4. Accounts appear in online accounts & pantheon mail
5. click on unified inbox -- office365 inbox is not included
6. Issue persists even when deleting the account and trying again

### Expected Behavior

All inboxes appear within the unified inbox, including the office365 EWS accounts. 

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by marbetschar** [comment]
OAuth2 authentication for Online Accounts is still in the works. Meanwhile you can add the Office 365 mailbox using IMAP/SMTP as described here: https://support.microsoft.com/en-us/office/pop-imap-and-smtp-settings-8361e398-8af4-4e97-b147-6c6c4ac95353

Adding OAuth2 support is related to https://github.com/elementary/portals/issues/19

**Comment by keithcdodd** [comment]
Thank you. 

Both of my accounts are connected & working in pantheon mail (by adding them in Evolution), it is simply that office365 account's inbox is not also added to the unified inbox, even though the gmail's one is included in the unified inbox.

I tried your suggested method for adding my Office 365 to see if that helps, but unfortunately it throws the error "verification failed: you must be working online to complete this operation" -- which I assume is related to your comment that OAuth2 for Online Accounts is still in the works since my office 365 is OAuth2. I had the same issue with my Gmail which is also OAuth2. These issues were fixed when I added them to Evolution.

So both my Gmail & Office365 with OAuth2 are connected to mail, but the issue is the inbox for the office365 account is not included in the unified inbox and I cannot find a way to fix that. I assume it is a bug because the individual inboxes work fine.

Thanks for the help!

**Comment by marbetschar** [comment]
For the unified folders to work they have to be pre-defined correctly im EDS. If you use Online Accounts to configure the accounts this is taken care of.

If you configure the accounts in Evolution, there might be some discrepancies we are not aware yet due to not officially support oauth yet.

Long story short: If you want to stick with oauth, you might have some luck by tinkering with the folder configurations in the account settings within Evolution (can't remember the exact details now, but you can re-configure draft folders - so maybe there is something similar for inbox too)

**Comment by keithcdodd** [comment]
Thank you. Unfortunately I do not have a choice with OAUTH2 for the office365. I will keep trying to tinker with the folders (so far no luck -- they appear to have the same/similar conditions to my gmail which is working properly with the unified inbox), but I appreciate the help! If I figure something out on that end, I will post here. If it helps narrow down the issue, within Evolution I can create a unified inbox search folder that works fine for both accounts, but I assume the process in pantheon mail with online accounts is significantly different.

Hopefully as oauth2 comes more onboard in the future, this will work better. Thanks again for the responses and help!

**Comment by marbetschar** [comment]
@keithcdodd I created a fix for the non-working Unified Inbox of Office 365 account: https://github.com/elementary/mail/pull/753 Would be great if you can give it a spin to see if it works on your end (in case compiling from source works for you)
