### ISSUE TITLE
Yahoo accounts impossible to set up

### ISSUE THREAD

**Issue by pislagz** [elementary/mail#739]
### What Happened?

> Could not save the e-mail account.
> IMAP verification failed: Could not log in. Please verify your credentials.

App up to date, no luck with connecting any of my Yahoo accounts to it using IMAP. Tried with every setting and port listed on [Yahoo Help](https://help.yahoo.com/kb/SLN4075.html) (surprisingly, the default `Server URL` in the `IMAP` and `SMTP` fields were different from the ones listed on Yahoo Help so I tried changing them as well, still nothing).

### Steps to Reproduce

1. Opened Mail
2. Due to the lack of any accounts connected, clicked the `Online Accounts...` button in the middle 
3. Tried several times to connect a few of my Yahoo accounts without luck, every single time there was a text saying _Setting up the email account..._  with a spinner animation for a couple of seconds after i clicked `Log In` button, then a following error occurred: 
![image](https://user-images.githubusercontent.com/77860645/144575596-01a1b67c-63a7-465b-948f-0229e2686d50.png)

Credentials are 100% valid, as I log in to browser mail with no problem.

### Expected Behavior

I wish it worked well as using browser or Thunderbird ugly client isn't nearly as pleasing as being able to imagine to use this sexy app.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

CPU: i5-9400F
GPU: GTX 1070 8GB
RAM: 16GB DDR4 2666MHz
OS: Up to date Odin 6

**Comment by marbetschar** [comment]
I _think_ you need to use an app password instead of your regular password to successfuly configure the account in Online Accounts:
https://help.yahoo.com/kb/SLN15241.html

**Comment by pislagz** [comment]
Worked as a charm. Many thanks! ✨

**Comment by pislagz** [comment]
Worked like a charm. Many thanks! sparkles

**Comment by pislagz** [comment]
Worked like a charm. Many thanks! ✨
