### ISSUE TITLE
Deleted messages seems to be permanently deleted instead of moved to Trash folder

### ISSUE THREAD

**Issue by casasfernando** [elementary/mail#748]
### What Happened?

When I delete a message in Mail, instead of moving it to the Trash folder, the message seems to be permanently deleted without warning.

This is dangerous because if you accidentally delete a message I found no way to recover it. 

### Steps to Reproduce

1. Select a message from Inbox.
2. Click on the trash bin icon to delete the message.
3. Check the Trash folder (either the one marked with the trash bin icon and the one called **Deleted** -please check separate [issue](https://github.com/elementary/mail/issues/749) that explain this-).

### Expected Behavior

Expected behavior: the deleted message should appear in the Trash folder.

Current behavior: the message is nowhere to be found. You can also use other email clients, web client or mobile device to confirm that the message is not in the email account anymore.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by kalmbach** [comment]
This is a duplicate from https://github.com/elementary/mail/issues/657

**Comment by marbetschar** [comment]
Confirmed. Thanks for Housekeeping @kalmbach!
