### ISSUE TITLE
Configurable refresh period

### ISSUE THREAD

**Issue by aral** [elementary/mail#752]
### Problem

It seems that currently Mail looks for new messages every ten minutes. It would be nice to be able to change this interval. e.g., I’d be much happier with a period of, say, 1 minute for my purposes.

### Proposal

Add a setting to Account Settings where you can change the default new message checking period for a mail account.

### Prior Art (Optional)

I don’t know off the top of my head but most email clients I’m used to today basically show newly received messages almost immediately.

**Comment by marbetschar** [comment]
For reference in case someone wants to tackle this:

We laid the foundation for this in https://github.com/elementary/switchboard-plug-onlineaccounts/pull/222 - so what this issue is basically all about is exposing this attribute in the GUI to make it configurable.

**Comment by kalmbach** [comment]
I was looking for an issue like this as an entry point to my involvement, I would like to grab this issue and this unnecessary comment is just to make me accountable. 🙂
