### ISSUE TITLE
Mail not clearly showing the compose dialog when replying/forwarding from the vertical ellipsis menu option

### ISSUE THREAD

**Issue by casasfernando** [elementary/mail#763]
### What Happened?

When replying/forwarding a message by clicking on the corresponding option in the vertical ellipsis menu on the message view:

![image](https://user-images.githubusercontent.com/15861819/151454660-2e2cfe46-b28f-4ec4-8bfc-b96d65b9206a.png)

Mail is not scrolling down to the compose dialog so if the message is long enough, the user will miss the reply dialog unless he scrolls down to the end of the message which may not be obvious. In my case I thought nothing was happening when actually the compose dialog opened down below, "hidden", under the message.

On the other hand if I click on the reply or forward buttons in the top row of Mail app:

![image](https://user-images.githubusercontent.com/15861819/151454574-a755c45c-914d-4495-a81c-397f0b990844.png)

the message view will automatically scroll down to the compose dialog.

### Steps to Reproduce

1. Open a long message (one that will exceed the message view pane size)
2. Click in the vertical ellipsis menu on the message (under the star)
3. Click on reply, reply all or forward.

### Expected Behavior

Current behavior: Mail is not scrolling down to the compose dialog so if the message is long enough, the user will miss the compose dialog unless he scrolls down to the end of the message which may not be obvious. The compose dialog is actually down below, "hidden", after the message.

Expected behavior: the message view will automatically scroll down to the compose dialog that was opened to reply/forward the message (same behavior as when clicking on the reply or forward buttons on the top)

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by leolost2605** [comment]
Closing as this should be fixed with #860
