### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by yajo** [elementary/mail#774]
### What Happened?

I installed the app from flaptak in https://appcenter.elementary.io/io.elementary.mail/

It is missing some icons:
![screenshot_2022-02-09_11-26-33](https://user-images.githubusercontent.com/973709/153191077-76d00f07-cda7-4df7-a036-ba336eb4e52f.png)

### Steps to Reproduce

1. Open it

### Expected Behavior

All icons should be displayed properly.

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
> flatpak run io.elementary.mail
Gtk-Message: 11:28:19.054: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:28:19.055: Failed to load module "canberra-gtk-module"

(io.elementary.mail:2): camel-WARNING **: 11:28:21.137: CamelIMAPXStore::get_folder_info_sync() reported failure without setting its GError

(io.elementary.mail:2): GLib-GObject-WARNING **: 11:28:21.266: ../gobject/gsignal.c:2732: instance '0x564f517a85c0' has no handler with id '862'

(io.elementary.mail:2): GLib-GObject-WARNING **: 11:28:21.266: ../gobject/gsignal.c:2732: instance '0x564f517a83d0' has no handler with id '831'

(io.elementary.mail:2): GLib-GObject-WARNING **: 11:28:21.267: ../gobject/gsignal.c:2732: instance '0x564f517a81e0' has no handler with id '211'
```

### Hardware Info

Fedora Silverblue 35. GNOME 41.

**Comment by danirabbit** [comment]
For Music we solved this by hardcoding elementary icons and stylesheet. It would probably make sense to do the same here: https://github.com/elementary/music/blob/main/src/Application.vala#L77
