### ISSUE TITLE
When deleting mail via delete key, the next message does not get automatically selected

### ISSUE THREAD

**Issue by gfavaro** [elementary/mail#799]
### What Happened?

Same as #

When selecting an email in the list of messages, pressing Delete will delete the message, but the next message in the inbox/list does not get selected, which means Delete cannot be pressed again to just delete the following message, and so on.

### Steps to Reproduce

1. Select an email in the inbox
2. Press Delete
3. Attempt to delete again for the next message without use of mouse

### Expected Behavior

When Delete is pressed, the message should get trashed/deleted, and the next message in the inbox should be selected/active to allow the user to act on it.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by stan-janssen** [comment]
This is resolved in the current version since #660. I think we can close this one.
