### ISSUE TITLE
port to webkit2gtk-4.0 [$20]

### ISSUE THREAD

**Issue by decathorpe** [elementary/mail#8]
`webkitgtk-3.0` has been considered deprecated and insecure for some time. It even has already been removed from the repositories that will become fedora 27 (for a reasoning, see [1]). This prevents me from building pantheon-mail for fedora, and could be considered a security risk even on elementaryOS.

geary has already been ported to `webkit2gtk-4.0` (see the upstream commit [2]). Maybe some of the work done there can be reused for pantheon-mail.

[1]: https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/AKVB363GFCHHJ5MTHGVYHYT6NLLTF5VM/

[2]: https://git.gnome.org/browse/geary/commit/?id=29b339c87dc11ccbfae14d0b1cb41ebbe08ed745

**Comment by cassidyjames** [comment]
Bounty added at https://www.bountysource.com/issues/44253773-port-to-webkit2gtk-4-0

**Comment by bil-elmoussaoui** [comment]
Is anyone working on this? Should I just port pantheon mail to webkit2gtk 4 or there's something else that should be added?

**Comment by danrabbit** [comment]
@bil-elmoussaoui there's a [rewrite branch](https://github.com/elementary/mail/tree/rewrite) that uses WebKit2Gtk4 and changes the backend to be EDS/LibCamel based instead. Personally, I think it would be better to spend development time there to get it up to feature parity so we can ship the new code base. But if you'd like to port the current code base to WebKit2Gtk4 that would be appreciated to :)
