### ISSUE TITLE
Missing move ability

### ISSUE THREAD

**Issue by pheonixo** [elementary/mail#800]
### What Happened?

Selecting move conversation only allows move to archive. Just switched to OS6 so assume missing code on new rewrite of Mail. This also includes the drop/drag method of moving emails to correct folders. This feature a must due to Yahoos service sends some emails to spam, mostly competitors of yahoo and att. I dislike their censorship but at least I could move to inbox to read as email was composed. I now have several emails in archive which I can not move back out and into correct locations, inbox now archive and inbox. PS can not build pre 6 series pantheon-mail due to ubuntu 18.04 code restrictions of dependencies.

### Steps to Reproduce

1. Select toolbar icon by usual right click
2. Moves to Archive no context menu for location
3. Or try drop/drag.
4. Attempted even old Geary alt/ctrl attempts fail

### Expected Behavior

To be able to place into one of the locations listed in sidebar, or from one location to another.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
No output failure
```

### Hardware Info

Ryzen 2400g, linux latest firmware updates, ubuntu 20.04.3 base, kernel 5.18.12, all software less than week old including developer files.

**Comment by Dahaniel** [comment]
+1 same issue on OS 7 Horus
