### ISSUE TITLE
Regression: no autoselection of next message anymore

### ISSUE THREAD

**Issue by ysbaddaden** [elementary/mail#807]
### Problem

When I delete a message, the following message is improperly selected. It looks like it's selected, but I must click the message to actually be able to keep interacting with it.

I can't mass cleanup my inbox quickly anymore and be done with 20+ minutes in a dozen seconds. I must click each message independently, which takes many minutes and is boring that I could be inclined to not do any cleanup, which is a bad behavior.

### Proposal

Restore the autoselect next message option from Elementary 5; at least have an option to enable/disable it —I can understand that we wouldn't want that behavior.

### Prior Art (Optional)

It worked in Elementary 5. Geary still has the option.

**Comment by tintou** [comment]
Oddly, this feature is implemented for archiving ( https://github.com/elementary/mail/commit/7aa857d45545220ce19839e7e20aa6ae6cb073b6 ) but not for deletion.

**Comment by davidmhewitt** [comment]
> Oddly, this feature is implemented for archiving ( https://github.com/elementary/mail/commit/7aa857d45545220ce19839e7e20aa6ae6cb073b6 ) but not for deletion.

#680

**Comment by stan-janssen** [comment]
@davidmhewitt I can confirm that #660 has solved this (I’m on elementary OS 7). I think this issue can be closed.
