### ISSUE TITLE
Regression: can't declare email aliases anymore

### ISSUE THREAD

**Issue by ysbaddaden** [elementary/mail#808]
### Problem

I redirect different emails to a single mail account. I need to be able to chose the identity I want to send each email with. I can't define email aliases anymore after upgrading to Elementary 6, and all emails are sent with the account email.

### Proposal

1. Bring back the ability to declare one or more email aliases for each account.
2. Bring back the ability to select the email to use when sending an email (on behalf of the mail account).

### Prior Art (Optional)

The feature was available in Elementary 5.

**Comment by nevillepark** [comment]
This is also mentioned in issue #636. 

It used to be that once you had set up email aliases in the application Evolution, they would appear in Mail. However, now there's no option to select which email addresses to use.

This would be very useful for me. I forward most of my mail to one address and use aliases to reply to messages.
