### ISSUE TITLE
The app email always crashes after opening an email.

### ISSUE THREAD

**Issue by PauloMonteiroT4Ts** [elementary/mail#809]
### What Happened?

The app email always crashes after opening an email.

### Steps to Reproduce

I open the application
I hope the emails load
I open an email
the app crashes

### Expected Behavior

No crashe

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

### Hardware Info

UM700
Quad-Core AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
AMD® Picasso
16,0 GiB de memória
512,1 GB de armazenamento (NVMe SSD)

**Comment by nevillepark** [comment]
More discussion at #814.

**Comment by lenemter** [comment]
Should be fixed by #825
