### ISSUE TITLE
Mail Keeps Crashing

### ISSUE THREAD

**Issue by Imauny** [elementary/mail#818]
When i open up the elementary mail app, it shows the email selected for a brief moment then the app crashes over and over. I'm on elementary 7 Horus, latest update.

**Comment by mluizvitor** [comment]
I can confirm.
The app crashes when I try to delete, mark as unread or update emails.
I'm on elementaryOS 7, fresh install with 2 Google accounts connected.

**Comment by joystickjedi** [comment]
Yup, same here just upgraded last week from Elementary 6.1 to 7. I open mail, can view 2-3 messages, then it just crashes.

**Comment by nevillepark** [comment]
Likely a dupe of #814.

**Comment by Dahaniel** [comment]
can confirm this, same happening here.

**Comment by lenemter** [comment]
Should be fixed by #825
