### ISSUE TITLE
Performance issues when trashing lots of conversations

### ISSUE THREAD

**Issue by lenemter** [elementary/mail#896]
### What Happened?

After https://github.com/elementary/mail/pull/888 trashing conversations became painfully slow. When you delete many conversations in a row mail freezes for a couple seconds.

### Steps to Reproduce

1. Open conversation
2. Delete it
3. Delete the next automatically opened conversation

### Expected Behavior

No freezes

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by lenemter** [comment]
Also for some reason after deleting many conversations they lag to be deleted from the messages list. Probably introduced by the same #888

**Comment by leolost2605** [comment]
So i just tried it but for some reason I don't have the same issue
Can you try with #895 as that fixes some criticals with freezing and thawing folders that were introduced with #888.

**Comment by lenemter** [comment]
Nope, still lags

Mail with #895:

https://github.com/elementary/mail/assets/80143868/f3b9325b-fbfa-4873-88c1-1e9803e719da

Mail before #888:

https://github.com/elementary/mail/assets/80143868/782fff82-0783-47fa-ac31-b5a7a6029f9e

**Comment by leolost2605** [comment]
Can you try with #897? That fixed the performance issues for me.
