### ISSUE TITLE
Send button off window if quoted message text is long

### ISSUE THREAD

**Issue by jeremypw** [elementary/mail#913]
### What Happened?

When trying to reply to a certain email with a long quoted thread the window just expanded off the bottom of the window and the contents could not be scrolled or the window resized to show the "Send" button.

This does not happen with all email senders - in most cases the thread is properly divided into individual messages and on replying to one of them a small window with a scrolled view and Send button appears

### Steps to Reproduce

1. Open certain long email threads where the previous messages are quoted
2. Reply to it
3. See unusable window.

### Expected Behavior

All email replies should appear in a resizable window limited to the screen size with a scrollable view and Send button. 

### OS Version

7.x (Horus)

### Software Version

Compiled from master branch

### Log Output

No terminal output is produced on opening such an unusable reply window.

**Comment by jeremypw** [comment]
A work around is to create a new message and then cut and paste the required quoted text into it.

**Comment by leolost2605** [comment]
Should be fixed with #894
