### ISSUE TITLE
Mail auto starts despite being turned off in application settings

### ISSUE THREAD

**Issue by lenemter** [elementary/mail#919]
### What Happened?

Mail (and Tasks) auto starts in window mode (not background mode) despite being turned off in application settings.

Mail installed from git
Portals stable
Application settings stable

### Steps to Reproduce

1. ???
2. Profit

### Expected Behavior

Mail doesn't auto start when disabled and starts in background mode when enabled.

### OS Version

7.x (Horus)

### Software Version

Compiled from git

**Comment by danirabbit** [comment]
Have you checked that you don’t have a leftover autostart file in /etc from a previous install?

**Comment by lenemter** [comment]
@danirabbit Found them in /etc/xdg/autostart/. Thanks!

**Comment by TomiOhl** [comment]
Has anything changed here recently? Deleting the autostart file from /etc/xdg/autostart/ solved the issue back then but in the past two weeks Mail keeps opening (windowed mode) whenever the system boots up.
Autostart is switched on in application settings but that shouldn't open the app (and it didn't up until like two weeks ago)
