### ISSUE TITLE
Translatability-related shortcomings

### ISSUE THREAD

**Issue by TomiOhl** [elementary/mail#943]
### What Happened?

The new signature editor window has untranslatable text:
![image](https://github.com/elementary/mail/assets/6696659/a5ccadbd-464c-40bf-9074-3d3523abe884)
I cannot find these string on weblate. I'm maintaining the Hungarian translation and it's on 100% (except some lines in the Extras folder - old changelogs). E.g. if I search for "no signatures clearly visible on the above screenshot:
![image](https://github.com/elementary/mail/assets/6696659/0e24783e-c92d-4bfa-aa81-cacf27273467)

The context menu in the editor window also has untranslatable text (apparently I cannot take screenshots when context menus are open, but that's an unrelated issue). I mean the menu with options like cut/copy/paste.

Another issue is related to the new multi-touch gestures.
Swiping to the right on a conversation, you get "Archive".
These string are translated, however, the string for the word "Archive" is used in two files:
- on the list item itself: [src/ConversationList/ConversationListItem.vala:94](https://github.com/elementary/mail/blob/master/src/ConversationList/ConversationListItem.vala#L94)
- on the sidebar as a folder name: [src/FoldersView/GroupedFolderSourceItem.vala:42](https://github.com/elementary/mail/blob/master/src/FoldersView/GroupedFolderSourceItem.vala#L42)

The problem: the first one is a verb, while the second one is a noun. These are the same in English, but they differ in some other languages (e.g. Hungarian).

### Steps to Reproduce

Have Mail v7.2.0 and open the mentioned parts while the system language is anything but english.

### Expected Behavior

All strings should be translatable.

There should be two separate strings for "Archive" - one for the noun, one for the verb.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by tintou** [comment]
Thanks for noticing and reporting the issue, I've pushed a fix at https://github.com/elementary/mail/commit/013f4100a6113166519dfb197983462cb29215c3

**Comment by TomiOhl** [comment]
Thanks! However, I'm afraid the strings for the context menu still aren't included, and could you address the problem with the Archive string, too?

**Comment by tintou** [comment]
I've fixed the Archive string issue but the context menu is created by Webkit and should already be translated, unsure what is going wrong there

**Comment by tintou** [comment]
Opened https://github.com/elementary/mail/issues/945 for this specific issue

**Comment by TomiOhl** [comment]
Thanks!
