### ISSUE TITLE
elementary/mail : no more icons ???

### ISSUE THREAD

**Issue by VinceFR25** [elementary/mail#985]
### What Happened?

icons of the menu disapeared ...

### Steps to Reproduce

nothing done in purpose.

### Expected Behavior

no more menu icons for elementary's mail, this afternoon ???

### OS Version

5.x (Hera)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Closing since OS 5 is no longer supported. OP, please install a recent release of elementary OS
