### ISSUE TITLE
No Unread badges in the dock

### ISSUE THREAD

**Issue by teamcons** [elementary/mail#996]
### What Happened?

other apps display a badge in the dock. Other emails apps, unread mails
mail doesnt do that

### Steps to Reproduce

receive mail
no unread mail badge in the dock

### Expected Behavior

how much unread mails ?

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Duplicate of https://github.com/elementary/mail/issues/290
